### ISSUE TITLE
Add CI Tests for quartz-mock

### ISSUE THREAD

**Issue by asalem1** [influxdata/ui#3565] opened 2022-01-12 13:20 UTC
We have continued to face challenges when modifying quartz-mock. We would like to prevent a situation where the mock is modified and unknowingly breaks other functionality, tests, etc.

Our first pass at ensuring this will be to add CI tests to run against the mock-quartz repo for all incoming PRs. This should ensure that we don't break any tests in the larger pipeline(s). 

*Note*: Below is context on where this issue started. It is possible that we will still want to go down this road of pulling mock-quartz internal but we are going to start with running tests.

## Historical Context

Right now, we've got a quartz-mock running in our CI pipeline so that we can test changes on the UI with a snapshot version of the Quartz API. Having our UI tests bound by an outside repo that we need to maintain and actively work on for development purposes is rough and makes development a headache. We should consider swapping out the mock-quartz repo by colocating the mock network responses with [msw](https://github.com/mswjs/msw). This should allow for us to develop against the mock API much more easily, have changes on the UI and mock API correspond without the need to sync quay images, and consolidate dependencies in one location. For an example on how to use msw, check this out:

https://kentcdodds.com/blog/stop-mocking-fetch#then-i-discovered-msw

**Comment by asalem1** [comment] 2022-01-27 17:59
An alternative to this is that we can keep going down this path and integrate the mock-quartz repo with our current CI tests so that we just add onto this infrastructure and have tests running against PRs to ensure CI stability

**Comment by jzahnd** [comment] 2022-02-07 18:58
We will start with CI integration for the repo and go from there.

**Comment by wiedld** [comment] 2022-02-25 20:37
Here is how quartz-mock is integrated into the CI pipeline:
1. Quartz-mock is published: 
    * https://github.com/influxdata/quartz-mock/blob/main/.circleci/config.yml#L20-#L25
    * https://github.com/influxdata/quartz-mock/blob/main/Makefile#L22-L30 
2. Quartz-mock is then integrated into the k8s-idpe, for the test env and remocal:
    * https://github.com/influxdata/k8s-idpe/blob/master/apps/test/quartz-mock/deployment.libsonnet#L33
    * https://github.com/influxdata/k8s-idpe/blob/master/env/test/local/twodotoh-dev/yml/apps-v1.Deployment-twodotoh-dev.quartz-mock.yml#L29 
3. K8s-idpe then publishes quay images used in the CI pipeline (monitor-CI), as well as using quartz-mock for remocal.
4. The e-commerce team is already moving to lock-step merge changes to their 2 repos:
    * Quartz
    * Quartz-mock
5. This means that any changes in quartz, which would break our UI in prod, will get reflected when our UI breaks with quartz-mock.

The problem is that changes in quartz-mock (and quartz) are not communicated, or the ramifications understood enough, to prevent breaking UI and lost UI dev hours. We are proposing to prevent quartz-mock changes being merged which would break the UI: for the purposes of forcing this communication to occur.

.

Following this pattern, this means that:
* Quartz-mock would follow the standard CI pattern we seen in all of the other repos.
* This pattern is :
    * run a monitor-ci pipeline, using the latest UI sha
    * failing CI pipeline if there are breaking changes.
* This would force communication, and merging of compensatory UI changes which can handle the change in quartz-mock.
    * The UI changes would handle the quartz-mock (and quartz) changes.
    * Additionally, the UI changes would need to be backwards compatible; in order to pass monitor-ci with their current (not yet updated) mock-quartz.

This is approach v1.

.

Approach v2 — not preferred imho.

I am arguing against the versioning of quartz-mock in the UI. Because in order to do so:
1. the k8s-idpe would need to also version their quay images etc in order to reflect their SHA + quartz-mock SHA.
2. Monitor-ci would need to handle the 2 SHAs
3. UI would need to call in these 2 SHAs
4. UI would need to version their mock-quartz SHA used.
5. If UI falls behind in their mock-quartz SHA….then we are not matching the latest quartz SHA in prod

**Comment by asalem1** [comment] 2022-02-25 21:35
Approach 1

**Comment by wiedld** [comment] 2022-03-11 00:34
Done.

**Closed by wiedld** 2022-03-11 00:34 UTC
Labels: kind/tech-debt, team/unity, dependencies
