### ISSUE TITLE
UI variable loss after dashboard crash 

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/ui#6300] opened 2022-11-09 19:49 UTC
## About the bug
This is a community reported bug: 
https://community.influxdata.com/t/dashboard-crash-v2-5-1/27251

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Run influxdb 2.5.1 in podman container
2. The dashboards eventually crash and removes the configured variables from UI.
3. Each cell is then filled with text resembling the following:
` error @3:36-3:37: record is missing label mac error @2:19-2:20: record is missing label timeRangeStart error @2:43-2:44: record is missing label timeRangeStop`

**Expected behavior:**
Preserve the variables. 

Thank you.

**Comment by aerogus** [comment] 2022-11-11 22:10
same kind of error with influxdb 2.5.1, CentOS 7.9

`error @7:81-7:82: record is missing label lieu error @3:19-3:20: record is missing label timeRangeStart error @3:43-3:44: record is missing label timeRangeStop`

**Comment by Jayclifford345** [comment] 2022-11-18 10:39
I can also confirm this bug as well. InfluxDB 2.5.1, Rasberry PI 64bit

**Comment by Jayclifford345** [comment] 2022-11-18 10:41
Community user: Hi, since my upgrade in 2.5.1, my dashboards crashed after a couple of seconds (maybe the first refresh ?) It seems the variables are gone and so the request is maybe mal formed ? the server return a 400 http code. (POST on /api/v2/query?orgID=xxx)

 https://influxcommunity.slack.com/archives/CH7C56X4Z/p1668205670959099

**Comment by aerogus** [comment] 2022-11-25 14:25
> Community user: Hi, since my upgrade in 2.5.1, my dashboards crashed after a couple of seconds (maybe the first refresh ?) It seems the variables are gone and so the request is maybe mal formed ? the server return a 400 http code. (POST on /api/v2/query?orgID=xxx)
> 
> https://influxcommunity.slack.com/archives/CH7C56X4Z/p1668205670959099

that was my comment in slack :)

**Comment by brcommander** [comment] 2022-12-02 22:26
same here after setting autorefresh. Even InfluxDB2 Metrics (default) don't show up.

**Comment by homanee** [comment] 2022-12-05 17:13
Running InfluxDB v2.5.1 community edition. Error message is "@2:19-2:20: record is missing label timeRangeStart error @2:43-2:44: record is missing label timeRangeStop". Getting this when displaying a dashboard. Since most recent InfluxDB upograde, in November. Seems to happen after some time, with manual or automatic refresh. Causes the laptop running the browser (on Ubuntu) to get very busy. Happens in Firefox and Chromium. No crash reports by the browsers.

**Comment by konichuvak** [comment] 2022-12-09 15:35
Experiencing the same issue here after upgrading to InfluxDB v2.5.1.
Even when the auto-refresh is off, after about a minute of opening the dashboard the variables disappear from the menu bar a `This dashboard does not have any cells with defined variables` banner appears and none of the windows can reference variables anymore. Refreshing the browser page fixes it, but only until it crashes again next minute. 
This behaviour is observed regardless of the type of the variable used, i.e. map/query/csv.

Server: [5b6fdbf](https://github.com/influxdata/influxdb/tree/5b6fdbf05d)
Frontend: [822e216](https://github.com/influxdata/ui/tree/822e216)

**Comment by oneofthemany** [comment] 2022-12-19 13:07
as a course of analysis the same issue also presents itself in 2.6

**Comment by aerogus** [comment] 2022-12-19 13:38
The issue is still here after upgrading to 2.6. Maybe with a longer delay before crash

**Comment by Jayclifford345** [comment] 2022-12-19 13:40
Hi all,
Thank you for your testing. We are still looking into the issue. We thought reverting the UI back to a previous build would solve this issue for now. It would be of great help if you wouldn't mind also providing your system specs.

**Comment by jeffreyssmith2nd** [comment] 2022-12-19 13:58
@oneofthemany & @aerogus: Can you post the commit hash for the server and frontend that is shown on the login screen? Can you also make sure to do your browser's equivalent of a "hard refresh" to make sure it is using the latest frontend code?

**Comment by aerogus** [comment] 2022-12-19 14:17
<img width="371" alt="Capture d’écran 2022-12-19 à 15 02 05" src="https://user-images.githubusercontent.com/767901/208444923-1f01bfcb-d017-4ab9-918b-913731351052.png">

InfluxDB v2.6.0
Server: 24a2b62
Frontend: cbab7db
Server OS: CentOS Linux release 7.9.2009 (Core)

Dashbord after some seconds :
<img width="649" alt="Capture d’écran 2022-12-19 à 15 07 13" src="https://user-images.githubusercontent.com/767901/208445194-0172b2f2-899e-47ee-9479-b4fac2d20659.png">

I want to open dev tools (Firefox 108.0.1, MacOS Ventura 13.1) to monitor js console but can't manage te reproduce the bug now. Maybe the "disable http cache" had really permit the assets to be reloaded ...

I'll add a new answer if the bug is back.

**Comment by aerogus** [comment] 2022-12-19 14:41
Bug still here , some screenshot from the log console : 

<img width="778" alt="Capture d’écran 2022-12-19 à 15 39 11" src="https://user-images.githubusercontent.com/767901/208450838-81be8f5e-7f7d-4647-8252-876dfd98ddab.png">

<img width="616" alt="Capture d’écran 2022-12-19 à 15 39 57" src="https://user-images.githubusercontent.com/767901/208450843-d0e516dd-e333-4fc7-9dab-3786e4c46108.png">

<img width="465" alt="Capture d’écran 2022-12-19 à 15 40 09" src="https://user-images.githubusercontent.com/767901/208450846-18074712-073d-4b1d-9e5e-e41380a98730.png">

**Comment by philjb** [comment] 2022-12-19 15:09
Here's the issue on the cloud side: https://github.com/influxdata/ui/issues/5062

**Comment by oneofthemany** [comment] 2022-12-19 15:24
> @oneofthemany & @aerogus: Can you post the commit hash for the server and frontend that is shown on the login screen? Can you also make sure to do your browser's equivalent of a "hard refresh" to make sure it is using the latest frontend code?

InfluxDB v2.6.0Server: [24a2b62](https://github.com/influxdata/influxdb/tree/24a2b621ea)Frontend: [cbab7db](https://github.com/influxdata/ui/tree/cbab7db)

**Comment by oneofthemany** [comment] 2022-12-19 15:32
> Hi all, Thank you for your testing. We are still looking into the issue. We thought reverting the UI back to a previous build would solve this issue for now. It would be of great help if you wouldn't mind also providing your system specs.

I am running Influx in a podman container - This has tested on a HP Z2 G4 SFF workstation running Fedora 37, Raspberry Pi 4B running Fedora 37, Rock5b running Armbian 5.10 and all exhibit the same issue so it's not hardware or ecosystem independent.

I have also tested across Firefox and Chrome and get the same crash also.

**Comment by konichuvak** [comment] 2022-12-19 21:37
The issue seems to be fixed on arm64 after upgrading to 2.6.0
```
wget https://dl.influxdata.com/influxdb/releases/influxdb2-2.6.0-arm64.deb 
sudo dpkg -i influxdb2-2.6.0-arm64.deb
```

**Comment by homanee** [comment] 2022-12-20 05:31
The problem appears to be gone running InfluxDB v2.6.0 (Server 24a2b62, Frontend cbab7db) on Armbian 22.11.1 Jammy (with Linux 5.15.75-rockchip64). No error messages about the variables after running for some time. No longer is the laptop running the browser, showing the display running hot.

**Comment by oneofthemany** [comment] 2022-12-20 09:30
> @oneofthemany I am unable to reproduce on 2.6.0. That being said, a possibly related bug was discovered and fixed recently in the UI. Do you have the ability to run a custom build to see if it fixes things for you since you're clearly about to reproduce?
> 
> This is an x86 build, if you need an ARM build too just let me know.
> 
> [influxd](https://drive.google.com/file/d/15HzJZL2XreeuhS_bhLDbprceMBK6ak1f/view?usp=share_link)

I am running influx in docker - do you have a build for that?

Also how many variables do you have in your dashboard as that appears to influence the crash?

FYI I have 15 variables on my dashboard and noticed the crash after adding the 10th or so.

**Comment by oneofthemany** [comment] 2022-12-20 09:32
> The problem appears to be gone running InfluxDB v2.6.0 (Server 24a2b62, Frontend [cbab7db](https://github.com/influxdata/ui/commit/cbab7dbe5e4a08136f75fa0a0ad6f504f1d5fc8f)) on Armbian 22.11.1 Jammy (with Linux 5.15.75-rockchip64). No error messages about the variables after running for some time. No longer is the laptop running hot when showing the dashboard in Firefox.

how many variables are on you dashboard?

**Comment by homanee** [comment] 2022-12-20 10:17
> > The problem appears to be gone running InfluxDB v2.6.0 (Server 24a2b62, Frontend [cbab7db](https://github.com/influxdata/ui/commit/cbab7dbe5e4a08136f75fa0a0ad6f504f1d5fc8f)) on Armbian 22.11.1 Jammy (with Linux 5.15.75-rockchip64). No error messages about the variables after running for some time. No longer is the laptop running hot when showing the dashboard in Firefox.
> 
> how many variables are on you dashboard?

No variables in use on this dashboard. Note that before upgrading to v2.6.0, the dashboard did not use variables either. And on v2.5.1, the dashboard without variables led to the problems described in this thread.

**Comment by jeffreyssmith2nd** [comment] 2022-12-20 13:47
@oneofthemany Here is a docker image, thanks for the help in testing. I was only testing with the default time range variables, and was able to see it in 2.5.1 and not in 2.6.0. I will try to test with a large number of variables too.

`podman pull quay.io/jsmith_influxdata/influxdb:test-dashboard-fix`

**Comment by oneofthemany** [comment] 2022-12-20 16:18
> @oneofthemany Here is a docker image, thanks for the help in testing. I was only testing with the default time range variables, and was able to see it in 2.5.1 and not in 2.6.0. I will try to test with a large number of variables too.
> 
> `podman pull quay.io/jsmith_influxdata/influxdb:test-dashboard-fix`

the container does not load

`{"msg":"exec container process `/entrypoint.sh`: Exec format error","level":"error","time":"2022-12-20T16:17:28.000430207Z"}`

**Comment by jeffreyssmith2nd** [comment] 2022-12-21 13:52
Sorry for the delay, had some build environment issues. There's now 2 builds available, one x86_64 and one arm64.

`podman pull quay.io/jsmith_influxdata/influxdb:dashboard-testing-x86`
`podman pull quay.io/jsmith_influxdata/influxdb:dashboard-testing-arm64`

**Comment by oneofthemany** [comment] 2022-12-22 12:28
> 

what's different in these builds as I don't see the issue? - currently only tested ARM64

**Comment by oneofthemany** [comment] 2022-12-22 12:29
> Sorry for the delay, had some build environment issues. There's now 2 builds available, one x86_64 and one arm64.
> 
> `podman pull quay.io/jsmith_influxdata/influxdb:dashboard-testing-x86` `podman pull quay.io/jsmith_influxdata/influxdb:dashboard-testing-arm64`

What's different in these builds as I am not seeing the issue, well not as of yet anyway :)

**Comment by jeffreyssmith2nd** [comment] 2022-12-22 13:57
@oneofthemany The only change in this branch over 2.6.0 is an update to the flux-lap to fix a situation where it would panic fairly easily. If you do end up encountering the issue, please let me know, otherwise we will plan to get a 2.6.1 out with an updated UI build with this fix. Thanks again for the help in testing.

**Comment by oneofthemany** [comment] 2022-12-22 22:03
@jeffreyssmith2nd so it would appear that by fixing one you have fixed the other 🙂

Thanks !!!

**Comment by jeffreyssmith2nd** [comment] 2023-01-19 20:56
Closing this as we haven't seen any new reports. Please open a new issue if the same issue is encountered.

**Closed by jeffreyssmith2nd** 2023-01-19 20:56 UTC
Labels: kind/bug, team/ui
