### ISSUE TITLE
Data Explorer Time selection always assumes Local Time

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ui#6133] opened 2022-10-20 17:48 UTC
The time selection widget always the time you select is in local time and then the `Local`/`UTC` toggle converts the time. This means it is impossible to select a time in UTC, you must know the Local time you want to select. This is counter productive because the reason I want to work in UTC is because I want to ignore timezones. For example say I am working in a team that spans multiple timezones. Its common for one person to find some interesting data and share the UTC time for that data. So now I want to go see that same data. I want to be able to simply put in that UTC time into the date selector and query the data. Instead I am forced to first convert that UTC time I know into a local time so that the UI can convert it back to UTC.

1. Open time selection box
2. Make sure the UTC toggle is selected
3. Attempt to put in this time range 2022-10-18T12:00:00Z to  2022-10-18T17:00:00Z
4. You can select the day easily i.e the 18th but even typing in the box its always interpreted as a local time

**Expected behavior:**

When the Local vs UTC is selected as UTC the text in the time boxes is interpreted as a UTC time

**Actual behavior:**

When the Local vs UTC is selected as UTC the text in the time boxes is interpreted as a Local time

**Visual Proof:**

![image](https://user-images.githubusercontent.com/3771906/197019886-81df209f-89b5-4168-9af4-cf88125cbecc.png)

Note that the start time is written as  `2022-10-18 12:00` but if you look at the actual time range selected its ` 2022-10-18T18:00:00Z`. I am currently 6 hours west of UTC.

Same thing is true for the stop time, written as `2022-10-18 17:00` but the actual time range is ` 2022-10-18T23:00:00Z`

## About your environment

Cloud

**Comment by wiedld** [comment] 2023-02-08 22:05
Duplicate of https://github.com/influxdata/ui/issues/6451, which also has a PR up for code review. Closing.

**Closed by wiedld** 2023-02-08 22:05 UTC
Labels: kind/bug, team/ui, team/automation
