### ISSUE TITLE
Notebooks: Ability to resize all panels (especially script editor)

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#912] opened 2021-03-19 03:18 UTC
Given: I am in a notebook
And: there is any panel
When: I see LargeDraggableResizer -https://influxdata.github.io/clockface/?path=/story/layout-draggable-resizer-family--draggableresizer
Then: I can click to drag the resizer to increase **vertical** height

### Design Notes

Design Lead @juliajames12

This resize experience will also impact how we currently show resizing of the simple table (see ticket here: TBD)

**Comment by drdelambre** [comment] 2021-03-23 22:51
is the problem here that the default panel height is too large?

**Comment by drdelambre** [comment] 2021-03-29 23:55
![Screenshot from 2021-03-29 16-54-07.png](https://images.zenhubusercontent.com/5e3b1c99342de3102fa83e1d/f8023aa5-99d4-4174-8c1c-b22a3df37cd7)

if it gets too small, the value of the function panel is.. questionable

**Comment by russorat** [comment] 2021-03-30 16:10
in this case, the user has moved the panel to be small? we aren't auto resizing right?

**Comment by russorat** [comment] 2021-04-21 17:50
this is a blocker for using a notebook as a script editor. if you have any decent sized script, you can't view the preview and the script on the same page.

**Comment by juliajames12** [comment] 2021-04-27 23:24
@drdelambre @russorat @jzahnd 

Just updated this issue with a prototype and some design notes. Let me know if you have any questions! I'll go ahead and create a separate issue for updating resizing of the simple table for consistency and will link.

**Comment by drdelambre** [comment] 2021-04-28 16:10
hey @juliajames12 
if you take a peak at the image i put in the comments, the issue isn't with the ability to resize the column, it's that resizing makes the function lookup interaction completely unusable. we need that panel's interaction to be decoupled from the height of the query

**Comment by juliajames12** [comment] 2021-04-29 15:39
@drdelambre Thanks for the clarification. Currently working on a solution to decouple the functions section from the script editor panel height in the updated prototype for Notebooks. Took my previous prototype out of this issue and will replace with the new one once it's ready. 

Also, as you mentioned to me over Slack, we have an existing component called LargeDraggableResizer. Let's go ahead and apply to every panel (including replacing drag to resize on the simpletable). Side-note: we're going to slightly tweak that component to be a little more subtle, knowing that we want to apply it several places. There's a separate ticket to tweak that component here: https://app.zenhub.com/workspaces/clockface-5d54876e6ee5d53e5986b53e/issues/influxdata/clockface/615

If the Flux Function Panel is too small to be usable, the user can just resize the panel. No hardcoded min/max values. Let LargeDraggableResizer properties do their thing.

**Comment by mnorriswalker** [comment] 2021-05-21 16:38
New resizer via Clockface version 2.8.0 (2021-5-20) courtesy of @daviddkkim and @juliajames12 

[PR](https://github.com/influxdata/clockface/pull/618)
[TSX ](https://github.com/influxdata/clockface/blob/master/src/Components/DraggableResizer/DraggableResizer.tsx)

**Comment by jzahnd** [comment] 2021-05-25 21:10
We would not resize downsample or output to bucket.

**Comment by jzahnd** [comment] 2021-06-01 13:47
Note this has been moved to an epic with stories for each panel, closing this issue in favor of the epic.

Epic is here: https://github.com/influxdata/ui/issues/1562

**Closed by jzahnd** 2021-06-01 13:47 UTC
Labels: area/notebooks, enhancement, team/ui, team/unity
