### ISSUE TITLE
Notebooks(Alert): Alert messages are being received as spam

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/ui#3707] opened 2022-01-26 14:06 UTC
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. In AWS EC2 set up a micro instance with a simple HTTP listener that echos messages back to the console
2. Open Influxdbv2 (note that during this test the feature flag 'notebooksNewEndpoints') was set
3. Add test data to a bucket with data points that will trigger a critical threshold alert
4. Create a new Alert Notebook
5. Create a query based on the test data
6. In the alerts section define a threshold designed to trigger an alert notification 
7. In the endpoints section select HTTP and set the URL to the EC2 instance.  In this case plain HTTP with no tokens or authentication. 
8. Generate more test data with timestamps in the future and values to trigger the notification
9. Export the Notebook as a task 
10. Monitor the EC2 instance console for messages

**Expected behavior:**

Expected to receive one notification, just as when a similar Check-Endpoint-Rule is created with classic alerts. 

**Actual behavior:**

The listener is receiving scores of alerts.  This spam is repeated at a pulse equal to the value of the "Check Every" field in the Notebook alert definition. It keeps repeating well after the last data point has passed. 

From the message content, it appears a message is generated for every point in the data set.

**Visual Proof:**

**Console before creating/activating task**
![ClassicCheckHTTPNotifiyListenerConsole01](https://user-images.githubusercontent.com/25881301/151170607-e8735f35-dc2e-42f0-9ea2-4e4805d210a9.png)
Note one message from the traditional Check-Endp-Rule configuration in Alerts. 

**The Alert Definition**
![NotebooksAlert01](https://user-images.githubusercontent.com/25881301/151170761-eb6d512e-13dd-41bf-affe-38ffb6a11b1e.png)
Associated data set to be added below. 

**Console after notfication triggered(first time)**
![NotebookGeneratedCheckNotifications01](https://user-images.githubusercontent.com/25881301/151174159-211fcd6b-ba4c-4ba9-8ce5-6fb26be38686.gif)

**Note Similar Behavior with Slack Notification**
![NotebookGeneratedCheckNotificationsSlack01](https://user-images.githubusercontent.com/25881301/151175973-409f2b59-3591-456b-8666-d4c996d3d2fa.gif)
This was also encountered when exploring notifications with Slack a couple of days ago. 

## About your environment

**Environment info:**

Testing in K8S-IDPE remocal. 

last UI commit
```
commit a918e664f19a21d33b21fe2c19c7cac8aa01c573 (upstream/master, origin/master, origin/HEAD, master)
Author: Palakp41 <palak@influxdata.com>
Date:   Tue Jan 25 17:16:27 2022 -0800
```
last K8S-IDPE commit
```
commit 84c1d4fd7f71ca41759a5f31e3c245c59f3bd4da (HEAD -> master, origin/master, origin/HEAD)
Author: Hercules Mango Churchill <alchemy@influxdata.com>
Date:   Wed Jan 26 02:00:44 2022 +0000
```

**Data Set**
```
jsoucno,jev=haf mag=8.1
jsoucno,jev=haf mag=8.75
jsoucno,jev=haf mag=7.99
jsoucno,jev=haf mag=7.3
jsoucno,jev=haf mag=6.67
jsoucno,jev=haf mag=6.5
jsoucno,jev=haf mag=6.398
jsoucno,jev=haf mag=6.158
jsoucno,jev=haf mag=6.0631
jsoucno,jev=haf mag=6.61
jsoucno,jev=haf mag=6.72
jsoucno,jev=haf mag=7.28
jsoucno,jev=haf mag=8.25
jsoucno,jev=haf mag=8.6
jsoucno,jev=haf mag=9.34
jsoucno,jev=haf mag=8.76
jsoucno,jev=haf mag=7.88
jsoucno,jev=haf mag=8.094
jsoucno,jev=haf mag=32.25
jsoucno,jev=haf mag=6.06
```
Second to last point intended to trigger alert. 

**LIstener Used**
for convenience

```javascript
const fs = require('fs')
const express = require('express')
const app = express()
const port = 3000
const https = require('https')
const privateKey = fs.readFileSync('./ssl/express-selfsigned.key')
const certificate = fs.readFileSync('./ssl/express-selfsigned.crt')

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.post('/', (req,res) => {
        console.log('POST')

        let body = ''

        console.log(`HEADERS: ${JSON.stringify(req.headers)}`)

        req.on('data', (data) => {

                console.log(`DATA: ${data}`)
                body += data
        })

        req.on('end', () => {
                res.writeHead(200, {'Content-Type': 'text'})
                res.end(`received: \n ${body} \n`)
        })

//      res.send('POST received\n')
})

app.listen(port, '0.0.0.0', () => {
  console.log(`Example app listening at http://0.0.0.0:${port}`)
})

const httpsServer = https.createServer({key: privateKey, cert: certificate}, app)
httpsServer.listen(443, () => {
   console.log(`Example app listening for HTTPS`)
})


```

**Comment by subirjolly** [comment] 2022-02-23 14:52
I was looking at `mailgun` and seems like the sandbox domains will be marked as spam if the recipients aren't authorized. So, it might just be a dev thing.

<img width="359" alt="image" src="https://user-images.githubusercontent.com/1637395/155343639-0b64e413-c071-41f2-a69b-2e3b29e9f48b.png">

**Comment by karel-rehor** [comment] 2022-02-24 16:11
@subirjolly 

I've tested against Mailjet and Mailgun and this issue is present.  I've received dozens of emails on our test account within the space of a minute.  The to and from addresses are authorized at the services.  The problem is the bulk of notifications generated all at once to one recipient.  

   1. Many of the notifications are based on points which just happen to be in the time frame and but do not match the threshold criteria. 
   2. And then, if the time frame is N times larger than the check interval, the check will continue to run N times, until the trigger event passes out of the time frame. But this second issue is one that a user can fall into through inattention and I think the UI could help a user avoid this, if they do not want to be notified of the same incident multiple times.

**Comment by wiedld** [comment] 2022-03-11 02:40
## Summarizing previous findings:
* we are getting notebook alert notifications being received as spam.
* the reason could include rules on the receiver (as @subirjolly pointed out), but at least definitely is caused by us triggering multiple alerts at once --> spamming the endpoint (as @karel-rehor pointed out).
* the root cause is due to porting over of flux syntax from the alerts part of the application (outside of notebooks), into notebooks alerts...without there being a real understanding of what flux is doing.
* As a result of this incorrect flux, we are (at a minimum) spamming the endpoints.

Below is a review of how alerting works, inside and outside of notebooks. And what the flux query is doing.

## Alerts part of app:
For the non-notebook alerts, the basic task flow is: (1) alert check (a flux task), and then (2) notification rules (another flux query).
Alert checks work by setting statuses in a _monitoring bucket.
Notification rules work by reading these^^ statuses, and then triggering a notification.

Actual user UX:
1. user creates an "alert check"
    * example flux:
    ```
    crit = (r) => r["fieldName"] > 20.0
    data
        |> v1["fieldsAsCols"]()
        |> monitor["check"](data: check, messageFn: messageFn, crit: crit)
    ```
    * output is writing `statuses` to a _monitoring bucket, as per the docs:  https://docs.influxdata.com/flux/v0.x/stdlib/influxdata/influxdb/monitor/check/
    * note that the crit method here (`crit = (r) => r["fieldName"] > 20.0`) is the same as our trigger method.
2. user creates a separate notification rule.
    * example flux:
    ```
    // fetch all statuses from the monitoring bucket
    statuses = monitor["from"](start: -11m)
    // filter for statuses with a certain label (e.g. level)
    crit = statuses |> filter(fn: (r) => r["_level"] == "crit")
    // now filter this subset, for the given time interval
    all_statuses = crit
         |> filter(fn: (r) => r["_time"] >= experimental["subDuration"](from: now(), d: 10m))
     // for all statuses passing this^^ criteria, trigger a notification endpoint
     all_statuses
         |> monitor["notify"](
             data: notification,
             endpoint: endpoint(
                mapFn: (r) => {
                    body = {r with _version: 1}
                    return {headers: headers, data: json["encode"](v: body)}
                },
            ),
         )
    ```
    * monitor.from() is reading the `_monitoring` bucket, as per the docs:  https://docs.influxdata.com/flux/v0.x/stdlib/influxdata/influxdb/monitor/from/


## Current pattern in notebook alerts:
The pattern we use in notebooks, is just wrong. It is demonstrative of how we have been learning flux on the fly, (the minimum needed), while debugging to observed behaviors. IMHO, this is why we keep hardcoding incorrect flux queries (including myself here too 🤦🏼‍♀️ ).

Here is what our general notebook alerts look like:
```
trigger = (r) => r["fieldName"] > 20.0
messageFn = (r) => "${strings.title(v: r._type)} for ${r._source_measurement} triggered at ${time(v: r._source_timestamp)}!"

// take our data
task_data
    |> schema["fieldsAsCols"]()
    |> set(
        key: "_notebook_link",
        value: "url",
    )
    // write to the _monitoring bucket
    |> monitor["check"](
         data: check, 
         messageFn: messageFn, 
         crit: trigger)
    // pipe this data into triggering an alert notification.
    // note that we are not reading statuses from the _monitoring bucket
    // we are piping in the full (unfiltered) task_data...so we spam-call this monitor.notify()
    |> monitor["notify"](
        data: notification,
        endpoint:
            http.endpoint(url: "http://ec2-13-52-255-26.us-west-1.compute.amazonaws.com:3000")(
                mapFn: (r) => {
                    body = {r with _version: 1}

                   return {headers: {"Content-Type": "application/json"}, data: json.encode(v: body)}
                },
            ),
    )
```
So we are just plain doing it wrong, in notebook alerts. 

## Proposed solutions.
We should be either:
(A) writing statuses to the monitoring bucket, then read this current status (over the time interval) and triggering only 1 alert notification at a time
or
(B) never bother with the _monitoring bucket, and just trigger the notification endpoint based on a filtering (threshold filter, and time integration filter)...without addition data munging to ensure we trigger the notification endpoint only once.

If we think any data being stored in the _monitoring bucket would be useful for ourselves (or the user) in the future, then I would recommend option A.

**Comment by wiedld** [comment] 2022-03-11 05:06
Also note, this pattern^^ of incorrect flux correct occurs every single endpoint we have in the notebook alerts.

**Comment by wiedld** [comment] 2022-03-22 01:20
Doing partial fix PR 4067.

There will still be some additional/multiple alert notifications, because both the notebook alert and the broader Alert System (the Alert Check) will be triggered.
see comment here: https://github.com/influxdata/ui/issues/4081#issuecomment-1074584517

**Comment by wiedld** [comment] 2022-03-28 18:13
Going to move this over to the PR stage, since we really cannot do anything else about this with the current integration with the monitoring package.

**Closed** 2022-04-26 22:35 UTC
Labels: kind/bug, team/ui, severity/sev-4, bonitoo, team/unity
