### ISSUE TITLE
Another CSP issue - can't read readme for community templates

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#1067] opened 2021-04-01 17:00 UTC
I installed the earthquake community template, and when I click on 'view readme' I get an error in the Javascript console: Refused to connect to 'https://raw.githubusercontent.com/influxdata/community-templates/master/earthquake_usgs/readme.md' because it violates the document's Content Security Policy.

**Comment by russorat** [comment] 2021-04-01 19:02
dupe of: https://github.com/influxdata/idpe/issues/9952

**Closed by russorat** 2021-04-01 19:02 UTC
Labels: kind/bug, team/ui, team/unity
