### ISSUE TITLE
Export to dashboard query audit

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#319] opened 2020-11-17 17:08 UTC
this thing is throwing queries every time I type! that stuff should be fixed in place with either better rerender logic or use of the query cache.

![Peek 2020-11-17 09-06.gif](https://images.zenhubusercontent.com/5e3b1c99342de3102fa83e1d/72cd6005-bab6-46e9-ae85-2ab29e86c918)

**Comment by Asalem1** [comment] 2020-11-30 18:59
this shouldn't actually be querying when you type since you aren't actually searching the API for an existing bucket. I'll take a look at this

**Comment by Asalem1** [comment] 2020-12-04 22:37
Hey @drdelambre I can't reproduce this, mind if i close it?

![cant-repro.gif](https://images.zenhubusercontent.com/5e1e17ea1d813696a893d77a/9fa72@696-d991-4e20-9231-6ffc5822759c)

**Closed** 2020-12-04 22:39 UTC
Labels: kind/bug, team/monitoring
