### ISSUE TITLE
Multi Org Phase 2 - Enable duplicate org names in the same region across different accounts

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#4951] opened 2022-07-01 19:45 UTC
ON HOLD - The system doesn't support this yet. 

Waiting on: https://github.com/influxdata/idpe/issues/14999  (Adam, Stacie, & Vinay))

**Comment by ALuckette** [comment] 2022-09-26 16:09
Enabling duplicate org names per account is dependent on the compute team:

https://github.com/influxdata/idpe/issues/15596
https://github.com/influxdata/idpe/issues/15576
https://github.com/influxdata/idpe/issues/15597
https://github.com/influxdata/idpe/issues/15598

FYI @kristinarobinson @hoorayimhelping @ChitlangeSahas @wdoconnell

**Comment by wdoconnell** [comment] 2022-09-26 16:20
For feature context - I think this means we can't implement the 'duplicate of same org in current account' error message yet (which relies on assumption that the orgs retrieved for this account from quartz represent the only constraints on org names).

**Comment by ALuckette** [comment] 2022-10-19 12:39
Yes, that's correct. Thank you for typing that in here! :)

**Comment by wdoconnell** [comment] 2022-12-21 21:49
This was a placeholder for idpe work, which was completed by @saraghds

**Closed by wdoconnell** 2022-12-21 21:49 UTC
Labels: team/ui, team/dumplings, blocked
