### ISSUE TITLE
Href not displaying right

### ISSUE THREAD

**Issue by zoesteinkamp** [influxdata/ui#3528] opened 2022-01-07 07:03 UTC
## About the bug
So in atleast the client-libraries/javascript-node page there is an improperly tagged href. As seen here. Should be a quick fix, not sure if its in an issue in other client library pages.
`
For more detailed and up to date information check out the <a href="https://github.com/influxdata/influxdb-client-js" target="_blank" rel="noreferrer">GitHub Repository</a>`

**Visual Proof:**

<img width="1539" alt="Screen Shot 2022-01-07 at 12 00 02 AM" src="https://user-images.githubusercontent.com/6667389/148504792-6dda3ab3-aa21-4e1c-b9ad-9f67e4a3c832.png">

**Comment by jzahnd** [comment] 2022-01-10 18:52
This is a duplicate of https://github.com/influxdata/ui/issues/3239.

**Closed by jzahnd** 2022-01-10 18:52 UTC
Labels: kind/bug, team/ui, team/unity
