### ISSUE TITLE
Unknown level type provided to ...

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [influxdata/ui#4128] opened 2022-03-17 12:16 UTC
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

- Edit a notifcation rule and change the condition from "Is equal to" to "changes from"

**Expected behavior:**
- It changes the dropdown.

**Actual behavior:**
- Frontend crashes and shows error message. 

**Visual Proof:**
![image](https://user-images.githubusercontent.com/7256303/158806347-067eb52b-b800-4dd0-a16d-552db0da886b.png)
![image](https://user-images.githubusercontent.com/7256303/158806383-3c165fb2-e8c6-400d-a046-31c96a86068a.png)

## About your environment

**Environment info:**

- Latest influxdb2 running in docker.

**Config:**
N/A

**Logs:**
N/A

**Performance:**
N/A

**Comment by kristinarobinson** [comment] 2022-03-18 21:11
@MathiasDeWeerdt Thanks for logging this issue.  Would you mind grabbing a screen capture of where you are editing?  In the Cloud UI there isn't a dropdown for editing Notification Rules.  I would like to see if I can reproduce this the Cloud UI as well, so I need to verify exactly which values you are attempting to change.  Thanks so much!

**Comment by wdoconnell** [comment] 2023-03-03 16:48
Closing due to absence of response from submitter.

**Closed by wdoconnell** 2023-03-03 16:48 UTC
Labels: kind/bug, team/ui, team/edge
