### ISSUE TITLE
Cloud Failed to fetch variables - can't load any dashboards with Safari

### ISSUE THREAD

**Issue by gomazu** [influxdata/ui#3419] opened 2021-12-13 17:34 UTC
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. using Safari, click on any dashboard
![Screen Shot 2021-12-13 at 9 32 06 AM](https://user-images.githubusercontent.com/63891737/145860615-151d36d1-03d6-42fd-88b1-5af8ca881a4a.png)
![Screen Shot 2021-12-13 at 9 29 50 AM](https://user-images.githubusercontent.com/63891737/145860620-792cd344-6017-40bd-a3ab-294e71a4b846.png)
![Screen Shot 2021-12-13 at 9 29 15 AM](https://user-images.githubusercontent.com/63891737/145860627-d03c10a2-355d-4489-b9c1-27de68152286.png)

2. ...
3. ...

**Expected behavior:**

**Actual behavior:**

**Visual Proof:**

## About your environment

**Environment info:**

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by kristinarobinson** [comment] 2021-12-17 21:09
@gomazu We recently deployed a fix to production that affects Safari browsers.  Can you verify that this problem still exists for you?
If it does, can you check the following?
Did you recently load a template?  If so, what was it?
Are you able to view dashboards with another browser (try Chrome)?
Are you able to view the `Variables` tab on the `Settings` Page?
Thanks. Kristina

**Comment by barbaranelson** [comment] 2021-12-22 21:04
Marc invited me to join his org, but I can't reproduce the issue, even in Safari on my mac. That account has a lot of templates, and a few of the variables refer to non-existent buckets, but that shouldn't cause it to crash.

**Comment by gomazu** [comment] 2021-12-22 21:08
Safari Version 15.2 (17612.3.6.1.6)

**Comment by gomazu** [comment] 2021-12-23 17:03
@barbaranelson tried Safari build 15.2 (17612.3.6.1.6) in a customer's environment with similar results.
![Screen Shot 2021-12-23 at 9 00 28 AM](https://user-images.githubusercontent.com/63891737/147271442-787965c5-5f54-4dcb-ab78-4eb3b24b84ca.png)
![Screen Shot 2021-12-23 at 8 59 42 AM](https://user-images.githubusercontent.com/63891737/147271445-95f807d7-203a-45a5-97b1-de21c99be5ca.png)

**Comment by gomazu** [comment] 2021-12-23 17:05
Placeholder for me to help replicate.  https://us-west-2-1.aws.cloud2.influxdata.com/orgs/4930a3d6870ceb57/dashboards/085d135c58657000

**Comment by hoorayimhelping** [comment] 2022-01-20 23:59
I also couldn't replicate this issue, either locally or in the org Marc invited me to. When inviting me, he said he hasn't noticed happening again. I think we can close this issue for now.

**Comment by barbaranelson** [comment] 2022-01-21 19:43
Closing out as we can't replicate this any more.

**Closed by barbaranelson** 2022-01-21 19:43 UTC
Labels: kind/bug, team/ui, team/dumplings

**Comment by philjb** [comment] 2022-08-29 14:56
recurred today: https://influxdata.slack.com/archives/C89G3JD2R/p1661769195346429
