### ISSUE TITLE
[bug] sometimes api token generation fails with a length error

### ISSUE THREAD

**Issue by philjb** [influxdata/ui#5277] opened 2022-08-03 17:05 UTC
## About the bug

When generating an all access token, i get an error saying the length of of the id must be 16 bytes. I have to refresh the page to get past the error.

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. unknown
2. generate api toke
3. observe error

**Expected behavior:**
no errors when making an api token or at least errors should be recoverable with steps on what to do.

**Actual behavior:**
api toke json id length error - and no token!

**Visual Proof:**

![Screen Shot 2022-08-02 at 9 15 50 PM](https://user-images.githubusercontent.com/13472206/182667372-9c0e0094-f2cd-4d64-8a93-e2bb4152b6c3.png)

<img width="1040" alt="Screen Shot 2022-08-02 at 9 15 59 PM" src="https://user-images.githubusercontent.com/13472206/182667386-c599930c-80c0-432b-b621-ec25a1f3e8ed.png">
<img width="359" alt="Screen Shot 2022-08-02 at 9 16 05 PM" src="https://user-images.githubusercontent.com/13472206/182667409-3c8dd9c7-d589-4963-b552-2cf8c3cc887e.png">

## About your environment

**Environment info:**
cloud2

related to #4992

**Comment by philjb** [comment] 2022-08-15 13:53
@blegesse-git asked me:

> Hi Phil, I've been looking into [this](https://github.com/influxdata/ui/issues/5277) issue you created and was wondering if you are still unable to create an all access token
> 
> I am not able to reproduce locally or in prod environment.
> My guess is that error is caused when token is trying to be created with no org or me id. I'm not sure what could be causing these two variables to return with an incorrect value, I'll have to investigate further.
> 
> But let know if the issue still persists or if it was a one time thing


Hey Beth - I have run into this error several times. When I run into it, it persists until I hard refresh the page. I don't do anything unusual when I hit the error. I log in, go to the tokens page and then create a token. Most of the time that sequence works but sometimes I get this error. Unless you've fixed it, I bet it will happen again. 

Would you improve the error messaging so it is more obvious what the end user should do? Is there other information that I should collect when I see this error next time?

**Comment by hoorayimhelping** [comment] 2022-08-15 15:51
@philjb can you remember if before generating the token, you logged in or switched orgs before refreshing the page?

**Comment by philjb** [comment] 2022-08-15 22:53
I haven't used the switching orgs feature at all so no for that. I was definitely logged in, but I couldn't say if i had logged in _in that tab_ or was using a previous cookie.

**Comment by blegesse-git** [comment] 2022-08-16 16:47
@philjb is it possible for you to reproduce this error? if not, maybe walk me through your flow? Including what environment you were on, type of account you signed in with, what you did before heading to the tokens page to create a token, or any other relevant information. I have not been able to observe this error without manipulating the code, which makes it harder for me to get the full picture on what's happening in the background.

**Comment by philjb** [comment] 2022-08-16 17:39
Hi Beth - It was almost 2 weeks ago. I don't have that information in my head anymore. I've shared in this ticket what I remember.

> type of account you signed in with

What types of accounts do we have? I didn't know we have more than one user account type.

**Comment by ALuckette** [comment] 2022-11-04 11:42
Hi @philjb, 

Apologies, we're having a hard time reproducing the bug you've experienced. 

Account type can be: Free, PAYG, or Annual Contract. 

Environments can be: Staging, Tools (New Tools), Production, or Post Production (monitor 301). Or you can share the URL, we'll see the environment in the URL based on your provider and region.

**Comment by ALuckette** [comment] 2022-11-04 11:44
@blegesse-git and @hoorayimhelping - Maybe we can work backward and dig into what triggers the error message shown in the ticket? It might be an issue with properly handling the error condition itself.

**Comment by blegesse-git** [comment] 2022-12-14 16:44
closing because issue has not been observed in the UI since the creation of this ticket.

**Closed by blegesse-git** 2022-12-14 16:44 UTC
Labels: kind/bug, team/ui, team/dumplings
