### ISSUE TITLE
Using some variables and/or types cause tenant data to become inaccessible 

### ISSUE THREAD

**Issue by influxlevan** [influxdata/ui#2134] opened 2021-07-26 18:02 UTC
Thank you for reporting a bug in InfluxData UI.

- Please ask usage questions on the Influx Community site.
  - https://community.influxdata.com/
- Please add a :+1: or comment on a similar existing bug report instead of opening a new one.
  - https://github.com/influxdata/ui/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+is%3Aclosed+sort%3Aupdated-desc+label%3Akind%2Fbug+
- Please check whether the bug can be reproduced with the latest release.
- The fastest way to fix a bug is to open a Pull Request.
  - https://github.com/influxdata/ui/pulls

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.
- It's hard to say exactly what step causes the system to fail but we seem to have caused this with at least 2 tenants (levan@influxdata.com and levan+demo@influxdata.com).
- Each time, we were building a set of dashboards (for demo) looking to specifically showcase the use of each type of variable /lookup-type.  As dashboards were being added and supporting queries were being tuned, the dashboard would eventually come back with some "variable" error (and no way to adjust/remove variables is available).
- 

**Expected behavior:**
Describe what you expected to happen.

**Actual behavior:**
Describe What actually happened.

**Environment info:**

- System info: Run `uname -srm` and copy the output here
- InfluxDB version: Run `influxd version` and copy the output here
- Other relevant environment details: Container runtime, disk info, etc

**Config:**
Copy any non-default config values here or attach the full config as a gist or file.

**Logs:**
Include snippet of errors in log.

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by kristinarobinson** [comment] 2021-08-02 20:56
@influxlevan -- Can you tell me whether you are using the Cloud native application or the OSS version of Influx when this happened?

Was the variable specifically named `/lookup-type` with the backslash in the variable name?

**Comment by influxlevan** [comment] 2021-08-03 02:41
Hi Kristina:

Thank you very much for following up.  The problem initially surfaced (on
cloud) when experimenting with various variables (all done through the
cloud UI flipping between map and csv types).  The problem was eventually
resolved by clearing the browser cache.  However, while present, no amount
of logging in and out resolved the issue.  Most likely this was caused by
the fact that we (sales engineers) have multiple accounts (to showcase for
various customers/types) and it may have been this logging in/out that
caused the problem.

Thanks again.

**Comment by kristinarobinson** [comment] 2021-08-03 16:16
@influxlevan -- Thanks for the information.  Given that you are unable to reproduce this, and clearing the cache resolved the issue, we are closing this item.  If you run across it again, please feel free to reopen with further details!

**Closed by kristinarobinson** 2021-08-03 16:16 UTC
Labels: kind/bug, team/ui
