### ISSUE TITLE
I can click a delete button in free single user org

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#935] opened 2021-03-22 21:02 UTC
## Acceptance Criteria [User Experience]

-  On the `/About` page we add a new option for 'Delete Organization'
- The 'Delete Organization' option is only visible to FREE accounts
- The 'Delete Organization' button is DISABLED if more than one user is associated with organization
- Clicking the disabled button opens a notification that "All additional Users must be removed from the Organization before the account can be deleted.", along with a link to the `/Users` page
- (if enabled) The 'Delete Organization' button opens a confirmation overlay
- The confirmation dialog displays alert that "This action cannot be undone" and a list of conditions 
- The confirmation overlay displays a toggle button for "I understand and agree to these conditions"
- Selecting the toggle button will enable the button to delete the account
- Clicking the 'delete' button will perform all actions necessary for account deletion

## Design 
https://www.figma.com/file/0gNEHedxD1J0bb1mkie6Aw/Free-Users-Account-Deletion?node-id=36%3A462

Error state: org is not actually single user
then redirect to support

Error: org is not actually free 
then redirect to the billing page

**Comment by corriganjohn** [comment] 2021-06-04 19:39
DUPLICATE of https://app.zenhub.com/workspaces/applicationsui-unity-606b1041215d5f0017898847/issues/influxdata/ui/934

**Closed** 2021-06-04 19:39 UTC
Labels: team/ui, team/unity
