### ISSUE TITLE
SPIKE - Time & Value handling with Query Results for Visualizations

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#6085] opened 2022-10-14 22:38 UTC
## **Spike Description**

<p></p>

When performing **SQL** queries against IOx, the results don't come back with "\_time" or "\_value" columns\.  This makes the existing visualizations beyond the tables views, by default, not show anything meaningful\.  You must edit the graph properties and change the x axis from "\_time" to "time"\.  You must also change the Y axis to a specific column name instead of it just being "\_value"\.  <span data-preserve-white-space></span>

<p></p>

We will need to find a way to retrofit our visualizations for IOx column names\.  Making "\_time" be "time" will be easy, but without the "\_value" the y axis selection may need to, by default, include all other columns returned \(besides time\); or at least just one column\.

<p></p>

This will need some thought to decide how best to handle this\.

**Comment by influx-product-manager** [comment] 2022-10-14 22:38
Link to subfeature: https://influxdata.productboard.com/feature-board/planning/features/15867750

**Comment by hoorayimhelping** [comment] 2022-10-18 14:48
>We will need to find a way to retrofit our visualizations for IOx column names. Making "_time" be "time" will be easy, but without the "_value" the y axis selection may need to, by default, include all other columns returned (besides time); or at least just one column.

Won't this also break any other visualizations, like Grafana as well? Is that a wise move, considering how much we've been criticized in the past for drastically changing implementations for very little customer gain (see the move from InfluxQL to Flux during the transition from v1 to v2 for example).

Is there something we can do that keeps IOx data consistent with existing interfaces, rather than forcing people to adapt to our changing interface?

If we can't, what affect will this have on people's ability to use our UI, or indeed make sense of their data given that we've been willing to direct people to other libraries rather than add features to our visualizations?

Is there some place I can look to find more information and background on this decision?

**Comment by hoorayimhelping** [comment] 2022-10-18 18:17
According to Paul:

>That is related to the SQL data model that IOx uses. If you execute a SQL query, you get back a table. `_time` and `_value` are Flux concepts. Flux queries against IOx return what you'd normally expect.

>IOx maps a measurement into a table. Tag and field names are columns. `time` is also a column.

**Comment by ALuckette** [comment] 2022-10-25 18:10
To check if an organization is an IOx org, you can use this selector https://github.com/influxdata/ui/blob/master/src/organizations/selectors/index.ts#L11, which will run after GetOrganizations.tsx is rendered (so basically it will work anywhere that isn't Setup.tsx, Authenticate.tsx, or GetFlags.tsx)

**Comment by wiedld** [comment] 2023-01-12 20:44
This analysis was done:
* under the QxBuilder
* on iox
* across all graphs currently supported in the Qx Builder

Summary:
* the graphs **currently do work**...but the problem is the data is not being displayed (by default) in a useful format:
   * The default selection of Y axis (etc per graph) is not correct.
   * The data is NOT show per dataseries within `iox.sql()`.
       * e.g. in SQL, by default, the "co" data field will display all sensor_ids (all tags) in the same line
       * verus in flux, it's grouped by all tags (per sensor_id)
* Additionally, we started addressing the question of "what are the Qx builder graphs for?", in order to scope what to build. And how much "magic" to apply.


## Defining the Purpose (in QxBuilder)
* **for the table:**
   * the goal:
       * is a direct representation of SQL query
       * make it match all other interfaces
       * (e.g. invokable scripts, portable copy/paste)
   * the view:
       * as the raw data comes back
   * the query:
       * do no extra background magic, or modifying the query
* **for the graphs:**
   * the goal:
       * data exploration
       * graph is NOT a direct representation of SQL query
           * to do that, we basically embed grafana
   * the view:
       * make the conceptual data model (influx data model) stay the same
       * translation: data series can be plotted (in some way)
   * the query:
       * Can modify as needed (a.k.a. do magic) --> the user will not use this query.
       * Perhaps a button => pop-up => this is the query we sent.
  
## Proposed Feature Comparison (Flux vs SQL) in QxBuilder graphs:
* same graphs
* same subset of graph options
* enable plotting per dataseries, with some UX differences
* for flux only:
   * default behavior is group on all tagKeys (per dataseries)
   * default behavior for large datasets --> drop/truncate data and plot partial
      * (this is our partially plotted lines, when we are missing part of the timerange) 
   * default behavior is to show all fields 
* for sql only:
   * expanded graph options (below are the new TODO options)
   * can choose which tagKeys to group. Still default to group on all tags (same as flux). 
   * default behavior for large datasets --> plot entire timerange
      * (uses new polyline feature, which uses math to selectively keep enough data to represent a data shape)
   * graphs are per field. Graph options to choose which field.

**Comment by wiedld** [comment] 2023-01-18 03:15
Marking this as done for now.
If we need a follow up spike for an iterative approach, then we can reopen (or make a new ticket).

**Closed by wiedld** 2023-01-18 03:15 UTC
Labels: team/ui, team/design, team/dumplings, team/automation, release/marty-23.01
