### ISSUE TITLE
Notebooks: When I use a Remote CSV input, I should be able to use aggregate functions in the visualization panel

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#2559] opened 2021-09-08 15:43 UTC
We would like to fix the bug that's blocking users from using an aggregate function on the visualization after a remote csv input is selected.

![Screen Shot 2021-09-08 at 11.43.17 AM.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/afdbb8e3-9cca-4680-8231-bb5fe5d6e2be)

**Comment by drdelambre** [comment] 2021-09-08 17:13
this hinges on the question: is the user expected to know the time range of the data, or is the system?
people seemed to loathe the former, as the user rarely knows the valid query period of the csv they've just been handed, and there's no way to get this from a csv before parsing it. it made our interface just look confusing and / or broken.
and what is the feasibility if the latter?

**Comment by drdelambre** [comment] 2021-09-08 17:14
wait. you can use the aggregate functions. is this a dupe of #2557?

**Comment by jzahnd** [comment] 2021-09-08 17:23
closing for duplicate

**Closed by jzahnd** 2021-09-08 17:23 UTC
Labels: kind/bug, team/ui, area/notebooks, team/unity, marketing-launch-block
