### ISSUE TITLE
Dashboard Usability - Copy button covers text when shrinking a cell

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4539] opened 2022-05-09 18:39 UTC

**Comment by Luckette** [comment] 2022-05-09 18:40
@mavarius @brandenTenbrink and @taramk can you add your design ideas to this ticket to address this issue?

**Comment by kristinarobinson** [comment] 2022-06-06 14:50
Duplicate of ui#4694, fixed.

**Closed by kristinarobinson** 2022-06-06 14:50 UTC
