### ISSUE TITLE
Annotations: modal closes prematurely if an error is made when setting ranges

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1764] opened 2021-06-22 16:27 UTC
it looks like if you make an error when you create an annotation by putting the end time before the start time for example, the modal closes and an error is shown, so the user has lost all their work. 

Is it possible to display the error and keep the modal open? as a note, it seems to work that way when editing an annotation.

**Comment by jrenee42** [comment] 2021-06-22 21:02
duplicate of #1751

**Closed** 2021-08-16 17:27 UTC
Labels: kind/bug, team/ui, team/dumplings
