### ISSUE TITLE
Band graphs broken/do not render.

### ISSUE THREAD

**Issue by philjb** [influxdata/ui#3404] opened 2021-12-08 19:50 UTC
## About the bug
Band graphs do not seem to work. Getting an error.

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Query for data in explorer page
2. Switch from "Graph" to "Band" graph plot type
3. Observe that an "error" message appears and there are errors in the console.

**Expected behavior:**
Band graph plots. No error.

**Actual behavior:**
Error seen.

**Visual Proof:**

![Screen Shot 2021-12-08 at 11 44 20 AM](https://user-images.githubusercontent.com/13472206/145274411-e9a98225-1f34-4533-92a4-0362d1dec72f.png)

![Screen Shot 2021-12-08 at 11 44 09 AM](https://user-images.githubusercontent.com/13472206/145274478-84062c48-e101-4f13-ba35-99473b0ff79d.png)

## About your environment

**Environment info:**
cloud2, us-west-2

**Config:**
na

**Logs:**
na

**Performance:**
na

**Comment by TCL735** [comment] 2022-01-11 01:18
Step 1 is vague here. I can complete the steps and not produce an error.

@philjb is there a more specific step 1 that can reproduce this error consistently? In other words, do you have a query that can reproduce this error? Thanks in advance for your help.

**Comment by philjb** [comment] 2022-01-19 01:38
I think i have a reproducible scenario.

Using this line protocol for a single point:
```
weather,location=nashville,county=davison,state=tn,tz=central,music=country temp=7000i
```

and this query for it

```
from(bucket: "phil")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "weather")
  |> filter(fn: (r) => r["_field"] == "temp")
  |> filter(fn: (r) => r["location"] == "nashville")
//   |> yield(name: "mean")
```

Then band graph has an error but then if you uncommen thte yield the band graph plots fine.

I get the same results on safari anf firefox. It appears that the band chart needs the `yield` in the flux.

**Comment by TCL735** [comment] 2022-01-20 01:52
Band graph must have a yield. Furthermore, the yielded name must be in the options (open Customize) under the "Main Column Name". The Script Editor does not automatically update "Main Column Name" with the yielded name.

This is not a bug. Closing this.

**Comment by philjb** [comment] 2022-01-20 04:20
I disagree. The UI (see screenshot) literally says to report a bug in this scenario. I will give that the band chart `Main Column Name` needs to match the `yield` name, which I did not know so that's my user error. The docs do imply this now that I've searched for it: https://docs.influxdata.com/influxdb/cloud/visualize-data/visualization-types/band/

If it is user error, the response from the ui `An InfluxDB error has occurred. Please report the issue here` is very unhelpful to the point of being misleading (says it's a bug but it's actually user error). Please think of this as a request to give a more informative error message. Someone else is going to report a bug for this because the interface is telling them to report it.

![Screen Shot 2022-01-19 at 8 09 56 PM](https://user-images.githubusercontent.com/13472206/150271846-9fd68125-1af6-4846-a09f-2b38cd6f9a6f.png)

**Comment by TCL735** [comment] 2022-01-21 00:31
Okay, there is also a deeper problem here.

Band graphs are relying aggregate functions to render properly. Originally, there were built with only Data Explorer, as that was the only visualization option available. Shortly after, Notebooks were developed, which do not (currently) use aggregate functions. Hence, Notebooks did not properly render Band graphs.

Further, in an effort to make Band graphs at least render-able in Notebooks, some critical state was no longer being passed into the View component that renders Band. This in turn caused Band graphs to easily break by not rendering properly even in the Data Explorer.

A deeper fix is needed than just a better Error boundary.

**Comment by TCL735** [comment] 2022-01-21 02:28
If there is a way to get all of the column names, and allow the user to select from just those names, then Band would be a lot easier to user. The side effect being that it would also be a harder to break, since only valid column names can be sent to the visualization's options for Giraffe to render.

**Closed** 2022-02-16 14:50 UTC
Labels: kind/bug, team/ui, team/dumplings
