### ISSUE TITLE
Filter in DataExplorer misses existing _field names

### ISSUE THREAD

**Issue by gefaila** [influxdata/ui#3609] opened 2022-01-17 15:22 UTC
I have a host that produces values for 6 _field with the letters THD in
When I write a flux script to chart all data for _fields containing /THD/ it finds 6 data fields.
![image](https://user-images.githubusercontent.com/69196723/149795883-c6b1e836-38ef-4e51-99f3-fb249d258cf9.png)

If I switch back to the "Query Builder" only *one* is listed
![image](https://user-images.githubusercontent.com/69196723/149793779-6df2b2b8-63b2-4f92-ad56-9d7debc5300f.png)

When I then type "THD" in the filter box for _field, *NO _fields are available* ???
The message "No Values found in the current time range" is displayed
![image](https://user-images.githubusercontent.com/69196723/149794308-57c113d4-2f7b-4ae5-bde3-eecf9954061a.png)

When I type "thd" in the filter box for _field, it finds THD_I2. (whereas previously it listed THD_V2 as being the only one!)
![image](https://user-images.githubusercontent.com/69196723/149794643-d8cf969a-4ecb-461e-84b2-3a12915701c6.png)

I have noticed similar behaviour with all kinds of other data and it's caused problems in the case that we start to act on the belief that there are no values for a certain parameter.

__Conclusion:__
The filter feature in Query Builder for _field is buggy, doesn't find data that is there and gives spurious results depending on whether lower or upper case is used.

**Comment by barbaranelson** [comment] 2022-01-19 23:57
@gefaila do you know approximately how many _field names you have? If you have more than 200, that is likely the problem here, because when we query the database to get the field names, we limit it to 200 for performance reasons.

**Comment by gefaila** [comment] 2022-01-24 09:22
Yes there are 400.  But this is a data explorer.  It's for exploring data.  It should have functionality that enables the customer to explore everything.  Imagine going to New York and being given a map that showed only *half* the city.  You wouldn't find that very useful would you?

**Comment by gefaila** [comment] 2022-01-24 09:22
:-)

**Comment by gefaila** [comment] 2022-01-24 09:32
Also I've spotted some even weirder behaviour ....
When I explore everything the database has for host "1935"  on 22nd Jan 2022 I get just FIVE _fields
![image](https://user-images.githubusercontent.com/69196723/150755701-2e4145ba-f378-4cee-b14c-a9704b5d22e7.png)

If I refresh the explorer and try again (same host, same date) I get TWELVE _fields
![image](https://user-images.githubusercontent.com/69196723/150755912-e4342d8a-7f6d-4434-b405-b14037053d63.png)

If I use a date range of the last 7 days (which includes 22nd Jan 2022) I get a different FOUR _fields
![image](https://user-images.githubusercontent.com/69196723/150756193-c7cdc037-760b-4940-a11a-5cadfdaf51aa.png)

If I write a flux script to count how many tags I have for this "host" for the last 7 days (which includes 22nd Jan 2022!), I get EIGHTY tags.

The behaviour I expect is

- When I have filtered by host, measurement, _time etc the UI lists *all* the tags
- in the case above (where there are 80) it should give *all of them*
- If it has truncated this list it tells me
- Ideally it doesn't truncate the results.  What does that really save given everything else that InfluxDB is doing !  I'm building queries that take 90 seconds to execute and return 10s of MB.  It does that fine without complaining.  Does a list being 200 tags shorter *REALLY* help Influx perform ?  Please just give us the whole list up to 1000 tags and let us get the full value out of an awesome product.

**Comment by barbaranelson** [comment] 2022-01-25 01:17
Hi @gefaila , we have increased the limits to 500 and are testing that internally. (We are mostly concerned about browser performance with much larger lists, not performance of the database which as you say can certainly keep up at these values). Once we are happy with the performance at 500, we can do another increase. Would you be willing to do a quick test in your account? If so, can you message me your org id (you can get it under Account/Settings) and I'll enable the feature flag for you so you can confirm it works for your measurements. Many thanks in advance.

**Comment by shriramb380** [comment] 2022-02-01 14:42
@barbaranelson customer is happy to test the 500 limit. His org id is

`faac9e69ed04ee08`


He says  that they have found that even if he  has only 20 tags *after* filtering by *host*

i.e. it appears that the 500 limit is not for the data for the host I filtered for in the Explorer but ALL hosts.

That is obviously undesirable.
So his question is then about the limit of 500.  Is it

A limit of the top 500 tags for *all* “host”s (where host is a tag)
A limit of the top 500 tags for a particular “host”

**Comment by barbaranelson** [comment] 2022-02-02 00:03
OK, I just turned on the feature flag so he should be able to see more of his metrics. Yes, the 500 limit is for whatever query we issue in the query builder. There is a flux query to populate the measurements dropdown, another flux query to populate the fields once a measurement has been selected. Each of these queries has a limit 500 applied to it.

**Comment by gefaila** [comment] 2022-02-02 10:05
HI Barbara, if you look above you will see proof that the 500 limit is not the issue. 
After filtering I only had 80 tags in the period.  Yet you can see that the Data Explorer was not displaying all of them

https://github.com/influxdata/ui/issues/3609#issuecomment-1019894914 

So can we go back a step *before* we try extending to the 500 limit.
Can you explain the above behaviour if the limit is 200?
I think the real issue is that there is a bug in the query that returns the tag list after filtering by "host".

**Comment by barbaranelson** [comment] 2022-02-02 23:42
Hi, it's all really a matter of timing in the query builder.  As soon as you select the bucket, we issue a flux query to populate the dropdown list (the one that contains the word host in your screen shot above).  We then issue a flux query to populate the second column based on the value you selected (or we default to populate the values in _measurement, by default).  Both of these queries have a LIMIT 500.  I'm not exactly sure why you're seeing partial results for queries that shouldn't hit that limit, but I would still be interested in seeing if the problem was resolved (at least temporarily) by the increased limit. That at least would confirm that the LIMIT parameter is contributing to the problem.  I'd also be happy to do some testing in your account, if that is something you would be comfortable with, or we can get on a zoom to go through it together.

**Comment by gefaila** [comment] 2022-02-03 10:59
Hi Barbara, 
I think it's really important to go back a step.
Can we remove the 500 limit and go back to what you had before.

Then please can you review my comments above which I believe prove that there is a bug in the 200 limit.
It is evidently not returning the top 200 _fields that are already filtered by "host".  It seems to be filtering the 200 without first filtering by "host".

Once I have your comments on the above (and no, you can see that the issue is *not* timing), then I think we'll move forward.

Does this sound acceptable?

**Comment by barbaranelson** [comment] 2022-02-03 18:10
OK, I've turned off the feature flag so your account will have the 200 limit. However, I'm not sure how to move forward from that. I don't have access to your data (unless you are willing to invite me to your organization) and what you are describing does not match the experience I am seeing in another account that has a large volume of data.

**Comment by gefaila** [comment] 2022-02-08 09:17
Thanks for doing that.
I have run the same query that I ran above https://github.com/influxdata/ui/issues/3609#issuecomment-1019894914 
It now behaves differently.
I therefore need to document this more fully because as it stands, it would be difficult to convince you that there is a problem.
However, it's happening again and again that that filter section does *not* return a full list of tags and that the list is populated by less than *200* items.  I will capture this more fully before reporting back.

But this issue is really causing issues as we attempt to utilise our data.

**Comment by barbaranelson** [comment] 2022-02-08 21:32
I agree. Bumping the limit to 500 was only a temporary solution to help you better utilize your data. Each flux query is non-deterministic in which data it returns, so when a limit is applied, we can get different experiences every time you refresh the page. We are working to change how this part of the UI works but it is complicated by the fact that time is the index into the database, and in the query builder sometimes you want the shape of the data, not limited by time.  So, I can't commit to how quickly we will have something better in place. In the meantime, if you want to stay with the 200 limit, that's fine, or if you'd prefer, I can change your account to have the 500 limit.

**Comment by gefaila** [comment] 2022-02-15 08:55
I have a proposed way forward.
First I'd like to clear up a UI bug which is related....
https://github.com/influxdata/ui/issues/3866#issue-1138376164

**Comment by gefaila** [comment] 2022-02-15 09:20
OK.  I'm able to demonstrate the bug to you in a way that proves (again) that is separate from the 200 Tag limit
I have a Notebook
https://eu-central-1-1.aws.cloud2.influxdata.com/orgs/faac9e69ed04ee08/notebooks/5fa821932b640000 
It starts with a Query Builder which has the following selected _fields
![image](https://user-images.githubusercontent.com/69196723/154030453-4e815493-42be-483e-912d-3081fef0d85e.png)

There is also a field called Ambient
Yet you can see that when you type "Ambient", the box just displays "...Loading" but does not find any _field called "Ambient"
![image](https://user-images.githubusercontent.com/69196723/154030744-a3f8c2fa-0dfe-4200-9d1e-65ace9f575f6.png)

At the bottom of the Notebook there is a **second** Query Builder.
This one behaves differently.  It **does** find the "Ambent" _field.
![image](https://user-images.githubusercontent.com/69196723/154031195-65084d91-8569-42f3-b16e-fa842398dbdb.png)


So I hope you agree that proves that there is something wrong with Query Builder not finding _fields that **are** there.
Can you help fix it?

**Comment by barbaranelson** [comment] 2022-02-15 20:46
I don't disagree that there is a problem. I am struggling with how to fix it, as based on screenshots alone, I can't reproduce the problem.  Any chance you can invite me to your organization briefly so that I can actually debug the issue with your data?

**Comment by barbaranelson** [comment] 2022-02-16 18:02
Thanks for inviting me to your organization. That should definitely help me to reproduce the issue you are seeing.

**Comment by gefaila** [comment] 2022-02-17 15:07
Hi Barbara, I hear that you can't replicate the issue.
Here's how to replicate:
1) go to https://eu-central-1-1.aws.cloud2.influxdata.com/orgs/faac9e69ed04ee08/notebooks/5fa821932b640000 
2) Type "Amb" in the Filter box where you are filtering by _field
![image](https://user-images.githubusercontent.com/69196723/154508911-8ab91bec-87c2-4a05-a288-2680f08555d9.png)
3) Observe that the filter doesn't find the _field  "AmbientDegC"
4) scroll to the bottom of the page where you see a second Query Builder which *does* find the _field  "AmbientDegC"

Can you reproduce it?

**Comment by gefaila** [comment] 2022-02-17 15:10
I've sent you an exported PDF of what I see.  Please send me an exported PDF of what you see
*Please don't modify the notebook because it'll no longer exhibit the bug*

![Bug3609](https://user-images.githubusercontent.com/69196723/154510498-088f7576-de3b-4e3d-8ce9-87aad454dfa4.png)
.

**Comment by barbaranelson** [comment] 2022-02-18 01:30
Thank you for your patience on this one.  Yes, I finally got to see what you've been describing.  It appears to be an issue with the flux we are generating, so I've asked the flux team to take a look. Basically, with the following query (which is what the UI generates):
```
import "regexp"
from(bucket: "PLC_Router_Data")
    |> range(start: 2022-02-15T00:00:00Z, stop: 2022-02-15T08:00:00Z)
    |> filter(fn: (r) => r["host"] == "Baskerville_Jmobile_PID_mk1")
    |> keep(columns: ["_field"])
    //|> group()
    |> distinct(column:"_field")
```
if I have the call to group before the call the distinct, only a subset of the valid values show up.  If I have the call to group before the call to keep or after the call to distinct, I see more values.

**Comment by gefaila** [comment] 2022-02-18 12:39
By the way, you can't call group before keep.
Because _fields may be of different types, so you have to do:

`from(bucket: "PLC_Router_Data")`
`    |> range(start: 2022-02-15T00:00:00Z, stop: 2022-02-15T23:00:00Z)`
`    |> filter(fn: (r) => r["host"] == "Baskerville_Jmobile_PID_mk1")`
`    |> keep(columns: ["_field"])`
`    |> distinct(column:"_field")`
`    |> group()`

**Comment by barbaranelson** [comment] 2022-02-18 21:21
We identified the problem (don't have a fix yet).  For performance reasons, we push down popular combinations of flux queries. In this case, we push down keep/group/distinct so it gets executed directly by the platform.  There is a bug in the implementation of the push down, so it's only returning partial results, for some larger data sets.  The reason that the problem went away when I changed the order of the flux commands, was because we no longer get the pushdown optimization, and the results are correct. The flux team is looking into this, to see what the problem is with the pushdown. Thank you for your patience (and your persistence).  Yes, I can see #3866 - as it's in the same code area, I'd like to see what the results of the code review yield to see if it addresses it too. This may well be two symptoms of the same problem.

**Comment by gefaila** [comment] 2022-02-21 11:04
Excellent.
Glad you are on the trail.
Is there a way that you can implement the alternative order **(keep|>distinct|>group)** in **our** account (without pushdown optimization) while a fix is being investigated?

**Comment by barbaranelson** [comment] 2022-02-23 00:43
Let me first get an ETA on when we can fix the pushdown. If it isn't going to be quick, then we can make the UI change as a temporary fix in your account.

**Comment by gefaila** [comment] 2022-02-23 14:35
Thanks.  I'll await your ETA.

**Comment by gefaila** [comment] 2022-03-01 18:14
Could you update me please on the fix progress?  Thanks.

**Comment by barbaranelson** [comment] 2022-03-02 17:21
Sorry, I have been at our sales kickoff meeting this week. Let me check and get back to you.

**Comment by shriramb380** [comment] 2022-03-07 12:03
@gefaila Apologies for the delay, I will get this chased with Barbara and get some feedback for you when she is online.

**Comment by barbaranelson** [comment] 2022-03-09 01:27
Hi, sorry for the slowness. The team has actually been working on a bunch of potential performance improvements in this part of the code, which is why it has taken a bit longer.  I pinged them again on this specific issue.

**Comment by gefaila** [comment] 2022-03-17 16:09
I'm confused ..
We already discussed the fix above ...

Where you have:
`|> keep(columns: ["_field"])`
 `|> group()`
 `|> distinct(column:"_field")`

You will replace this with 
`    |> keep(columns: ["_field"])`
`    |> distinct(column:"_field")`
`    |> group()`

Which you already tested yields the full list of values.

Since you tested the fix yields the results we both need, is there a layer of complexity to implementing this that I'm not aware of?

And if you can't do this, can you implement it for us without the pushdown optimization?

**Comment by barbaranelson** [comment] 2022-03-19 01:09
Do you have a recent example where it is still failing by any chance? I wasn't able to find one in my testing in your account. If you can identify another time range that shows this problem that would be great, as I can have the engineer take another look.

The 'fix' isn't a fix.  Removing a performance optimization is not a fix, as it will just lead to performance issues for people with a lot of data. That is why this particular sequence of flux calls was optimized in the first place.

Changing the UI so it has one query experience for your account, but a different experience for everyone else is a more significant work item, which is why I would prefer that the team focus on the new query work they are doing, which will change these queries, and potentially bypass the issue.

**Comment by gefaila** [comment] 2022-03-22 14:34
Yes.
1) go to https://eu-central-1-1.aws.cloud2.influxdata.com/orgs/faac9e69ed04ee08/notebooks/5fa821932b640000
2) Type "Press" in the FILTER by _field 
![image](https://user-images.githubusercontent.com/69196723/159506009-46eb9ccf-18a9-48dd-9c55-d80f26ab7ec4.png)
3) Verify yourself that the FILTER does not find the _field "Boiler Pressure"
4) Scroll down to the cell displaying "Boiler_Pressure" values
![image](https://user-images.githubusercontent.com/69196723/159506322-d5426ca4-d668-4341-8af5-1da5195b8407.png)

So yet again, that proves the bug.
FILTER does not display all the possible values, yet there are less than 200 (there are 153 to be precise)

**Comment by barbaranelson** [comment] 2022-03-22 20:32
Unfortunately, yet again, the problem went away before I could see it, which makes me feel like this is definitely related to compaction (which either solves the problem or moves it).  Here are screenshots from when I look at the notebook. All 153 tags are showing up in the filter dropdown.
![Screen Shot 2022-03-22 at 1 24 47 PM](https://user-images.githubusercontent.com/13143006/159570582-e5c626b4-35c0-43b9-824a-9be612973af7.png)
![Screen Shot 2022-03-22 at 1 25 09 PM](https://user-images.githubusercontent.com/13143006/159570605-8d7af58c-c813-49d0-afad-982a0d735134.png)

When you identified the missing metrics, how did you find them? Just wondering if there is something that I can do so we don't have a time delay between identifying the gap and troubleshooting the issue. Is it just that you know what metrics should or should not be there, or is there some search that I can do?

**Comment by barbaranelson** [comment] 2022-03-22 20:37
I also tried playing around with the time range, in case the local time ranges were different for you than they are for me, but it still didn't show the issue.
![Screen Shot 2022-03-22 at 1 34 03 PM](https://user-images.githubusercontent.com/13143006/159571460-dd079a04-023e-4811-ade1-f4adda8c89c5.png)

**Comment by gefaila** [comment] 2022-03-22 22:55
Please try to set the timescale to include a time span in the last 24 hours.

Then count the number of entries listed under FILTER _field and compare this with the last cell which counts the unique fields.

It's clear to see that the FILTER _field always misses some tags.

It's clear that it's not always the tags that I point you to.

So please can you tell me
1) the time range you set
2) the number of tags listed in FILTER _field (you'll have to don't then by hand)
3) the number of tags counted by the last cell.

Please experiment with recent times until you see they are different.

**Comment by barbaranelson** [comment] 2022-03-22 23:27
Cool. Let me give that a try and see if I can find some examples.

**Comment by gefaila** [comment] 2022-03-24 14:26
No we intentionally keep the data.  We are still deriving insights from data we collected years ago.  Since it's not costing us very much to store we keep it.

Long term we may compress it.  But the data reduction algorithms currently coded in Influx (windowing, mean, mode, min, max) are unsuitable because they have the undesirable feature of omitting outliers.  The type of algorithms that we (and I suspect other customers) would find much more useful  would be things like [RDP](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm).  This is ideally suited to compressing time-series data to retain all the extremes and sudden changes that form the most valuable component of data.

**Comment by barbaranelson** [comment] 2022-03-24 14:52
Thanks. That's helpful. I did manage to find another example of the issue, and the storage team is working on it, but they just wanted to know if there was anything different about how this data is processed. I'll let them know.

**Comment by barbaranelson** [comment] 2022-04-05 19:10
The fix is in production, and I confirmed that it solved the issue for the data sample that I had. Please let us know if you see anything different on your side, as you are a lot more familiar with the data than we are.

**Closed by barbaranelson** 2022-04-05 19:10 UTC
Labels: kind/bug, v2-prod-bug
