### ISSUE TITLE
Corrupt notebook (from column selector panel)

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#2469] opened 2021-08-26 00:29 UTC
I created a notebook in prod with a flux query.  I then added a column selector. It seemed to work at first, but then when I went to preview it again, I got an error.  Now the notebook shows with an error (instead of the column selector) and if I try to delete the column selector panel I get the error:

TypeError: Cannot read property 'family' of undefined
    at Object.disable (Sidebar.tsx:186)
    at Sidebar.tsx:225
    at Array.filter (<anonymous>)
    at Sidebar.tsx:223
    at Array.map (<anonymous>)
    at Y (Sidebar.tsx:221)
    at Vo (react-dom.production.min.js:150)
    at ki (react-dom.production.min.js:178)
    at Fa (react-dom.production.min.js:232)
    at Na (react-dom.production.min.js:233)
ra @ react-dom.production.min.js:198
i.componentDidCatch.n.callback @ react-dom.production.min.js:211
Ki @ react-dom.production.min.js:193
Xi @ react-dom.production.min.js:193
La @ react-dom.production.min.js:216
Ba @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
xs @ react-dom.production.min.js:250
As @ react-dom.production.min.js:249
Cs @ react-dom.production.min.js:248
Ts @ react-dom.production.min.js:251
Tn @ react-dom.production.min.js:85
A.Object.isExtensible.Object.isExtensible.e.___hb.e.___hb @ honeybadger.js:466

Notebook export is here:
{
  "data": {
    "orgID": "3f730102d8daf6ed",
    "name": "Untitled Notebook",
    "spec": {
      "name": "Untitled Notebook",
      "readOnly": false,
      "range": {
        "type": "selectable-duration",
        "label": "Past 1h",
        "lower": "now() - 1h",
        "upper": null,
        "seconds": 3600,
        "duration": "1h",
        "windowPeriod": 10000
      },
      "refresh": {
        "status": "paused",
        "duration": null,
        "interval": 0,
        "infiniteDuration": false,
        "inactivityTimeout": 0
      },
      "createdAt": "2021-08-26T00:18:28.755Z",
      "updatedAt": "2021-08-26T00:23:09.280Z",
      "pipes": [
        {
          "id": "local_8a43309f-1f8a-4695-8bf4-03a37215bd2b",
          "type": "rawFluxEditor",
          "queries": [
            {
              "text": "// Uncomment the following line to continue building from the previous cell\n// __PREVIOUS_RESULT__\n\nfrom(bucket: \"bnelson's Bucket\")\n  |> range(start: -15m, stop: now())\n  |> group(columns: [\"host\", \"_measurement\"], mode:\"by\")\n\n",
              "editMode": "advanced",
              "builderConfig": {
                "tags": [],
                "buckets": [],
                "functions": []
              }
            }
          ],
          "activeQuery": 0,
          "title": "Query to Run",
          "visible": true
        },
        {
          "id": "local_41472780-80fc-4e6e-b876-664230674d04"
        },
        {
          "id": "local_f072aef3-0655-4d51-b486-09f628352572",
          "type": "visualization",
          "period": "10s",
          "properties": {
            "type": "simple-table",
            "showAll": false
          },
          "title": "Validate the Data",
          "visible": true
        }
      ]
    }
  }
}

**Comment by genehynson** [comment] 2021-08-30 18:10
This is pretty bizarre. Any idea what the error was that you got when you ran the Preview before trying to delete the Column Selector panel @barbaranelson ? I can see the JSON is definitely corrupt - the Column Selector panel only has an `id` prop with no other properties, hence the "Error" state and the "can't read property 'family' of undefined" error. 

We currently don't do any validation of the panel objects themselves in notebooksd which is why the notebook was allowed to be persisted in this broken state. And ironically, I can create the broken notebook using the JSON you exported and shared above. 
![image.png](https://images.zenhubusercontent.com/5fceb17341f743ce2116433f/0067104e-b27c-4ac1-bb7d-f4e58846b9ad)

I can't seem to reproduce _getting into_ this situation though. So what I'm going to pursue is a safety net so if the UI finds a panel with missing properties, it still allows for deletion instead of throwing an error. That way if this does happen again, at least there is a way out of the situation.

And then as we work to decouple panels from notebooks, we can add in some validation in notebooksd so that we never actually persist broken panels in the first place.

**Comment by genehynson** [comment] 2021-08-30 20:01
Alright the referenced PR makes it so that you should be able to delete that Errored panel (once the PR is deployed to prod). I think that should lower the severity of this issue, but probably doesn't close it. I'm still unable to reproduce the original issue. Let me know if you're able to reproduce it again and how

**Comment by genehynson** [comment] 2021-11-11 17:25
Closing this issue since no one can reproduced after the attached PR was merged

**Closed by genehynson** 2021-11-11 17:25 UTC
Labels: kind/bug, team/ui, severity/sev-4, area/notebooks, team/unity
