### ISSUE TITLE
Bug: Wasted display space (small chart) with static legend

### ISSUE THREAD

**Issue by philjb** [influxdata/ui#4511] opened 2022-04-28 01:23 UTC
## About the bug

On the explorer page or when editing a dashboard cell, the static legend causes the legend and graph to waste a lot of screen real estate, making the graph small and hard to use. Resizing the browser window helps minimally. 

**Steps to reproduce:**
1. Create a query in the DE2. 
2. toggle on the static legend under customize3. 
3. see that the chart is small and there is wasted space as in the screenshots.4. 
**Expected behavior:**

don't wait screen space - the chart should grow to fill the available space like without the static legend.

**Actual behavior:**

chart stays small

**Visual Proof:**

these screenshot are taken with the same window size which is nearly fullscreen on my 1536x960 display.

<img width="1394" alt="Screen Shot 2022-04-27 at 3 50 18 PM" src="https://user-images.githubusercontent.com/13472206/165657542-3054d0ac-7e04-4dc5-91eb-9fa4a34f5021.png">
<img width="1383" alt="Screen Shot 2022-04-27 at 3 50 03 PM" src="https://user-images.githubusercontent.com/13472206/165657547-b249b47c-16bd-470e-8c5a-85186664b95c.png">

## About your environment

**Environment info:**
cloud2

**Config:**

NA

**Logs:**

NA
**Performance:**
NA

**Comment by TCL735** [comment] 2022-05-19 22:46
There is a font issue with Giraffe at the moment, which can cause different spacing. Let's wait until https://github.com/influxdata/ui/issues/4619 is resolved first

**Comment by TCL735** [comment] 2022-05-20 20:24
Update: the font issue not caused by Giraffe. The font issue is separate. While a change in font may cause a slight change in the spacing, it is only minor.

The real crux of this issue is user awareness. There is a height slider for the Static Legend that goes from 5% to 75% of the total height of the canvas (graph + static legend).

We are open to user feedback regarding the height slider and how well it addresses the issue of space usage.

**Comment by TCL735** [comment] 2022-05-20 20:25
@philjb any feedback or comments regarding the height slider for the static legend?

**Comment by philjb** [comment] 2022-05-20 20:43
> There is a height slider for the Static Legend that goes from 5% to 75% of the total height of the canvas (graph + static legend)

Didn't know about this - thanks @TCL735 

My ask would be that it pick the most space efficient height automatically.  It depends on the number of rows in the static legend. I could see a rule where if there are 10 rows or less, it will adjust the height to minimum needed to show all of the legend. If there are more than 10 rows, default to the heigh of 10 rows... and then the user can use the static legend scrollbar to see the rest of the legend.

**Comment by TCL735** [comment] 2022-05-23 20:10
It already tries to do this.

Here's an example of a single line in the static legend for a dashboard cell


![Image](https://user-images.githubusercontent.com/10736577/169898119-b135e2ca-79f3-4e1c-a5ea-c3c1da490a02.png)

**Comment by TCL735** [comment] 2022-05-23 20:10
Closing this.

**Closed by TCL735** 2022-05-23 20:10 UTC
Labels: kind/bug, team/ui, team/dumplings
