### ISSUE TITLE
Bug: Table scroll sticking for mouse wheel

### ISSUE THREAD

**Issue by OfTheDelmer** [influxdata/ui#3563] opened 2022-01-11 22:54 UTC
## Scroll sticking for mouse wheel

* Create a table view from a series
* Scroll with a mouse wheel (works fine with trackpad)

**Expected behavior:**
Table should scroll content up or down when wheel scrolls.

**Actual behavior:**
Scroll struggles to scroll up, but works fine when using Mac trackpad.

**Visual Proof:**

Table scrolling with mouse wheel

![scroll_2](https://user-images.githubusercontent.com/4994741/149033223-e1e126b7-303d-4e65-804f-22e18b2a552a.gif)

## About your environment

**Environment info:**
- Darwin 19.6.0 x86_64
- Cloud2

**Comment by kristinarobinson** [comment] 2022-01-14 21:45
@OfTheDelmer What browser(s) are you using?

**Comment by kristinarobinson** [comment] 2022-09-16 20:16
Duplicate of giraffe#788

**Closed by kristinarobinson** 2022-09-16 20:16 UTC
Labels: kind/bug, team/ui, team/dumplings
