### ISSUE TITLE
Customer issue: cursor in flux editor ends up in weird places

### ISSUE THREAD

**Issue by scbrickley** [influxdata/ui#609] opened 2021-02-04 18:03 UTC
Customer describes their issue in this thread from the community slack: https://influxcommunity.slack.com/archives/CJ2NXC6A2/p1612424925036400

This issue is one of two that they reported. Other is here: https://github.com/influxdata/ui/issues/608

**Comment by hoorayimhelping** [comment] 2021-03-01 23:02
duplicate of #756, which is slightly more descriptive.

**Closed by hoorayimhelping** 2021-03-01 23:02 UTC
Labels: kind/bug, team/ui
