### ISSUE TITLE
I am unable to join a collaborative server 

### ISSUE THREAD

**Issue by vaayu10** [influxdata/ui#1893] opened 2021-07-03 21:36 UTC

**Comment by kristinarobinson** [comment] 2022-06-06 14:57
@vaayu10 
Thank you for filing an issue.  In order to help, we need a few more things.

Can you tell us:
What happened when the error occurred?
How to reproduce it?
Are you using our Cloud or OSS product?  
What version?
What browser are you using?

Thanks for using InfluxDB.

**Comment by wdoconnell** [comment] 2023-03-03 17:36
Closing due to absence of a response from submitter.

**Closed by wdoconnell** 2023-03-03 17:36 UTC
