### ISSUE TITLE
Add the ability to choose schema type when creating a bucket

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2229] opened 2021-08-03 21:16 UTC
https://docs.influxdata.com/influxdb/cloud/api/#operation/PostBuckets

The create bucket api now supports an additional field that let's you specify implicit or explicit schema type for the bucket. 

this issue would update the create bucket modal to include the ability to set implicit (default) and explicit type.

acceptance crit:
 - as a user, i would like to create a bucket with an explicit schema in the UI

![image](https://user-images.githubusercontent.com/4805997/128087322-2bfb0d0a-741e-4ba2-a551-82c30a665d64.png)

**Comment by jrenee42** [comment] 2021-08-30 19:25
duplicate of #2490

**Closed** 2021-09-13 17:04 UTC
Labels: enhancement, team/ui
