### ISSUE TITLE
InfluxQL Support in Script Editor

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#6490] opened 2023-01-13 23:10 UTC
### EPIC Description

This EPIC is for the addition of a 3rd script type in the New Script Editor: InfluxQL.

**Background:**  The new IOx storage engine includes support for InfluxQL.   There are a number of Cloud 1 customers that are heavily invested in InfluxQL and it has been a barrier of adoption of Cloud 2 since it does not currently have InfluxQL support.  Adding InfluxQL to the script editor will reduce the reluctance of customers to move off of Cloud 1 and onto our IOx enabled platform.

### General Requirements & AC:

- When clicking on "New Script" inside the script editor, the user will be shown a 3rd option (in addition to the current SQL and Flux Options): InfluxQL
- When InfluxQL is selected the user we will be given a blank script editor, with a schema browser on the left and a display panel below - just like the Flux and SQL editors
- The user can type InfluxQL queries into the editor; upon hitting run the InfluxQL query will be executed
- When the Query Completes, the user will be shown a result table - like with Flux and SQL editing.  There is no need for a "graph" option.
- If there is an error with the query, the user will be shown the error

### Other Requirement Considerations

**InfluxQL LSP Support** - It is not required to integrate an InfluxQL LSP; the editing window can simple be a text edit block.  But if we do have something we could take from Cloud 1 that could easily be integrated, it is desirable - but again, not required.

**Schema Browser** - Like with the flux and SQL editor, the user should have a schema view.  The generation of the schema view itself does not have to come via InfluxQL queries; this can utilize SQL or Flux and doesn't have to be changed from its currently functionality to be used with InfluxQL.

**InfluxQL Injection** - It is desirable to be able to inject InfluxQL statements based on Schema Selections to be consistent with functionality from the other two languages; however, this is only a nice to have and is not a hard requirement.  Its importance is less than it was for SQL as that would encourage SQL use versus flux.  In this scenario, the user has SQL as an option already, so having this capability in InfluxQL is not quite as important.  

**Schema Sync** - While desirable to have this feature, it is definitely not a requirement.  It's importance is less than it was with the SQL editing function.

**Function Injection** - Function Injection is not required for InfluxQL editing; the function window can be hidden, like it is with the SQL editor.

**Result Window** -  Existing Result Window should be used if the table view works ok with the format of the data returned with InfluxQL.  The "search" capability is a nice-to-have if it can be retained.

**Date/Time Picker**- If InfluxQL Injection is not added, then there is no reason to have a date/time picker as the user will be manually entering their searches.  If Injection is included, then it would be desirable to have the date/time picker included.

**Load/Save** - Load/Save should utilize the scripts API and work just like SQL and Flux - just with a different  script"type" saved.

**Visualization/Graphs** - There is no requirement for Visualizations unless they somehow come for free - meaning the data comes back in the exact same format as flux and so the existing visualizations work automatically with them.  Otherwise, the Table/Graph button can be removed and only the table result needs to be displayed.

**Comment by wiedld** [comment] 2023-01-25 18:33
Duplicate of https://github.com/influxdata/ui/issues/6489. Closing.

**Closed by wiedld** 2023-01-25 18:33 UTC
Labels: epic
