### ISSUE TITLE
Multi Org Phase 1 - Remove existing Navigation Menu / Avatar

### ISSUE THREAD

**Issue by ChitlangeSahas** [influxdata/ui#5016] opened 2022-07-11 18:47 UTC
After Multi org feature flag is turned on, we would no longer need the old menu that is in the Nav bar:

![Image](https://user-images.githubusercontent.com/18511823/178336171-40375458-b135-4496-921c-0f74ed918343.png)

The new global header handles all of this.

**Comment by wdoconnell** [comment] 2022-09-01 20:56
Duplicate of UI issue #5564 

Resolved by UI PR #5572

**Closed by wdoconnell** 2022-09-01 20:56 UTC
Labels: team/dumplings
