### ISSUE TITLE
Spike: why so many flux parsers?

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#39] opened 2020-09-02 03:45 UTC
we have so many floating around for no reason. some are behind feature flags, some only apply to the raw data view, some are used for the lsp. Lets make one parser, with giraffe being the source of truth, and fill any gap lists between them. End state should be only one flux parser, and it should be in giraffe. and why so much code that isn't papaparse?

**Comment by desa** [comment] 2020-09-08 19:10
Link https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/idpe/8495

**Comment by Asalem1** [comment] 2020-09-21 16:03
### Overview

After a lot of trial and error, it appears that the `fromFlux` function from giraffe provides us with most of the outputs needed for the current UI to function with minimal adjustments needed in order to achieve the same the same outcome in the UI

### Why so many parsers?

While the sum total of parsers between the UI and Giraffe repos amount to 5 parsers, they can essentially be thought of as 2 parsers - one for the raw data table, and one for everything else. The reason for this is varied, but can essentially be thought of as code debt:  

- 1 parser in Giraffe is an almost exact duplicate of one of the parsers in the UI - this is due to the fact that RawDataTables is in the process of being transitioned over to Giraffe from the UI repo
- 1 parser in Giraffe is a slight variant of an existing Giraffe parser - this is due to the fact that updates to the existing parser created unexpected breaking changes in the UI when applied directly to the parser
- 1 parser in the UI is feature flagged and has yet to be successful in unifying the parsers

### Next Steps

Since the ultimate outcome of this is to transition the UI to depend upon 1 parser, the next step in this process should be to transition the use of the UI parser to the fromFlux parser wherever it is being used (https://github.com/influxdata/ui/issues/72).

In addition, we will want to create a data transformation layer to transform the fromFlux output into a schema that is suitable for the Raw Data Table view (https://github.com/influxdata/ui/issues/73)

**Closed** 2020-09-21 16:07 UTC
Labels: kind/tech-debt, team/monitoring
