### ISSUE TITLE
[bug] : disappearing dashboard variables: `record is missing label` error

### ISSUE THREAD

**Issue by philjb** [influxdata/ui#5062] opened 2022-07-14 19:31 UTC
## About the bug

While using dashboards with variables, I sometimes see `record is missing label` error across all my dashboard cells. I don't have steps to reproduce it. I've noticed more on dashboards with more cells and while scrolling but those might be bias because i'm usually in large dashboards and when i'm actively using it, i'm typically scrolling to see different cells while i think through a problem.

I'm attaching the screenshots i was able to capture. 

For this one, `env` is a variable in my flux queries.
<img width="692" alt="Screen Shot 2022-07-13 at 8 35 33 PM" src="https://user-images.githubusercontent.com/13472206/179066717-324792f8-b932-467b-a9ac-8fe67417b23d.png">

<img width="493" alt="Screen Shot 2022-07-13 at 8 05 38 PM" src="https://user-images.githubusercontent.com/13472206/179067510-2ea0a5af-573f-4c7a-97ff-2696a6fb6ac8.png">

You can see in this one that my variable dropdown bar also disappeared - it's like my dashboard forgot i had variables.
<img width="1080" alt="Screen Shot 2022-07-13 at 8 04 48 PM" src="https://user-images.githubusercontent.com/13472206/179067653-ddee4c6b-8b7d-457e-9065-c09d85095795.png">

From the console:
<img width="1414" alt="Screen Shot 2022-07-13 at 8 05 26 PM" src="https://user-images.githubusercontent.com/13472206/179067562-a16a464d-58c1-4a56-a397-356e42f4e5d0.png">
<img width="1452" alt="Screen Shot 2022-07-13 at 8 05 05 PM" src="https://user-images.githubusercontent.com/13472206/179067581-c932b168-bae7-40ca-97b2-7536bfdcbe1b.png">

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Have a dashboard with variables or even just `v.timeRangeStart`.
2. Unknown
3. observe error
 
**Expected behavior:**
No errors especially for built in variables like `v.timeRangeStart`

**Actual behavior:**

`record is missing label` error

**Visual Proof:**

see above

## About your environment

**Environment info:**
cloud2

**Config:**

na

**Logs:**

na
**Performance:**
na

**Comment by kristinarobinson** [comment] 2022-07-14 21:24
Discussing which team should triage.  Assignment to team forthcoming.

**Comment by abalone23** [comment] 2022-07-14 21:43
I have encountered this behavior as well.

**Comment by philjb** [comment] 2022-07-15 01:47
maybe related to: https://github.com/influxdata/ui/issues/5057/

**Comment by wiedld** [comment] 2022-07-15 17:35
#5057 is a separate, known issue.
https://github.com/influxdata/ui/issues/5057#issuecomment-1185756396

**Comment by wiedld** [comment] 2022-07-15 20:42
summary -- error is missing variables in UI application state. But the errors then get surfaced in 2 places.

Two parts:
1. when no global variables, we see any error in the LSP:
   * The LSP is sent an prelude doc with empty `option v ={}`.
      *  https://github.com/influxdata/ui/blob/master/src/languageSupport/languages/flux/lsp/connection.ts#L39-L40
   * the LSP errors on JSON.parse()
      * error in the console, seen by Phil
      *  https://github.com/influxdata/ui/blob/master/src/languageSupport/languages/flux/lsp/worker/utils.ts#L3
2. independently, it errors when the query is sent to the backend.
   * also because no variables in global state.


Action items: handle no variables errors more gracefully in the prelude (so no console.warn), and continue chasing down the intermittent missing variables in global state.

**Comment by wiedld** [comment] 2022-07-16 01:59
Recreated in monitor301, a total of four times.

### Not correlated with observed bug:
* there are at least three other console.error outputs, which are not correlated with the loss of the variables
  * a.k.a. I could get these errors while still able to run queries
  * one example was `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data` ->> for o() and send()
      * <img width="612" alt="Screen Shot 2022-07-15 at 6 33 08 PM" src="https://user-images.githubusercontent.com/10232835/179329470-b3c58ad9-9088-46b8-b9df-0777c6f79613.png">
      * that was due to this bug: https://github.com/influxdata/flux-lsp/issues/529

### Correlated:
* There are two errors which ARE correlated with the loss of variables/labels.
  * n = 4. Each time these errors occurred ->> lost variables. And vice versa.
  * steps in order:
    1. `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data` ->> for `E flux-lsp-browser_bg.js:285`
        * <img width="556" alt="Screen Shot 2022-07-15 at 6 35 03 PM" src="https://user-images.githubusercontent.com/10232835/179329711-2322190b-52b8-4f3c-99a1-7a9cd9026a7a.png">
        * <img width="429" alt="Screen Shot 2022-07-15 at 6 35 37 PM" src="https://user-images.githubusercontent.com/10232835/179329714-58b23986-c0e4-4287-88d5-8a1061d1c74f.png">
        * Note that the stacktrace above includes our utility method `parseASTIM()` which is used during our variable extraction.
           *  https://github.com/influxdata/ui/blob/master/src/variables/utils/astim.ts#L21-L24
        * It ends with the destroy() method on the LSP being called.
    2. That^^ error was always immediately followed by `TypeError: TextDecoder.decode: Decoding failed.`
        * <img width="570" alt="Screen Shot 2022-07-15 at 6 39 28 PM" src="https://user-images.githubusercontent.com/10232835/179329845-7aaccf07-4443-4653-99b0-8066a3328e51.png">
        * this is our general wasm import statement, now failing.
    3. Variables are no longer present in our dashboard.
        * because we use the same LSP util methods to determine which variables are there (existing in the dashboard queries), to populate the state in the dashboard.

## Next steps:
* chat with LSP team about failure protocol.
* still chasing down if there is another upstream failure that triggered this cascade.

.

https://user-images.githubusercontent.com/10232835/179330203-2bebfddb-083c-4244-9d76-037771dbbcfe.mp4

**Comment by btasker** [comment] 2022-07-19 14:35
I  encountered this earlier too, whilst working within a largeish dashboard.

When it first started occurring I was in the "edit cell" dialog adjusting a query

**Comment by wiedld** [comment] 2022-08-09 17:21
Subtasks (TODO):
- [ ] additional logging, for what is the problem
- [ ] remove this failure behavior. 
       * this is because we use the LSP to parse/extract variables.
       * once the LSP crashes --> we get this "missing variables" issue
       * removing this dependency, with the proper behavior: https://github.com/influxdata/ui/issues/5129

**Comment by marekpow** [comment] 2022-11-09 07:02
I have the same error. I have the latest version of InfluxDB and Telegraf.

**Comment by aerogus** [comment] 2022-11-10 21:22
Same here with last version 2.5.1 of influxdb

![influx](https://user-images.githubusercontent.com/767901/201208548-be848498-31bb-4358-90d4-b916c3862a30.png)

**Comment by philjb** [comment] 2022-12-08 03:22
i experienced this today on influx cloud2.

**Comment by aokholm** [comment] 2022-12-08 14:56
Seems pretty urgent to me. For me dashboard is almost unusable. I might open them quickly for a screen grab and then close it. Of cause difficult to know how many users is affected.

**Comment by aerogus** [comment] 2022-12-08 14:59
Pretty urgent to me too. In a very short term if it is not fixed, i plan to downgrade to v2.4.0 or ... switch to grafana...

**Comment by vettamatt** [comment] 2022-12-09 03:59
Makes a dashboard based upon telegraf data unusable for us, definitely needs fixed sooner rather than later.

**Comment by newah** [comment] 2022-12-13 13:25
basically a blocker.
dashboards work for ~15 seconds and then need a full reload of the dashboard.

**Comment by andig** [comment] 2022-12-13 13:37
...and been a blocker for 5 months. I've switched from Grafana because quality made it barely usable for me.

**Comment by wiedld** [comment] 2022-12-22 17:26
We pushed in a changed which decreases the chances of a wasm panic (the triggering event in the failure cascade). Early reports indicate that we are seeing less dashboard crashing with this error phenotype.

Please let us know of any status updates (improvements, or the same).

**Comment by mdisabato** [comment] 2022-12-22 21:23
I noticed a great increase in stability. Nice work.

Thank you!

Michael

**Comment by marekpow** [comment] 2022-12-22 22:10
Yes, the scenario which I posted above doesn't appear now. But I see the former starter screen. Is it means that you made a backward step in development?

**Comment by aokholm** [comment] 2022-12-25 12:35
Haven't seen the issue since upgrading to 2.6.0

**Comment by psychogun** [comment] 2022-12-29 00:59
> Haven't seen the issue since upgrading to 2.6.0

I have seen it :o

**Comment by aerogus** [comment] 2022-12-31 10:35
I will try v2.6.1 next week

**Comment by aerogus** [comment] 2023-01-02 10:47
I seems v2.6.1 resolve the bug. My dashboard is refreshing every 10 sec for 10min and it doesn't crash anymore.
Thank you, and happy new year :)

**Comment by wiedld** [comment] 2023-02-09 20:32
Confirmed that everything still seems to be working. CLosing.

**Closed by wiedld** 2023-02-09 20:32 UTC
Labels: kind/bug, team/ui, team/automation
