### ISSUE TITLE
hangup when editing script

### ISSUE THREAD

**Issue by rogpeppe** [influxdata/ui#443] opened 2020-12-17 18:28 UTC
**Steps to reproduce:**

In a script editor in Data Explorer, paste this text:
```union(tables: [a```
then start typing this text after the final `[a`:
```, ini```
This hangs up forever for me

**Environment info:**

Cloud2.
Chrome 87.0.4280.66

**Comment by drdelambre** [comment] 2021-03-01 23:50
cannot repro. @scbrickley did you fix this some other way?

**Comment by scbrickley** [comment] 2021-03-02 15:17
I'm not 100% sure, but it's possible this was caused by https://github.com/influxdata/idpe/issues/9592, which was resolved in https://github.com/influxdata/flux/pull/3487

**Comment by drdelambre** [comment] 2021-03-03 17:48
awesome. imma close this. as always, anyone should feel free to reopen it if the behavior is still floating around

**Closed by drdelambre** 2021-03-03 17:48 UTC
Labels: kind/bug, severity/sev-3, team/ui
