### ISSUE TITLE
Filter field endlessly displays "...Loading" in FILTER box (Query Builder in a Notebook)

### ISSUE THREAD

**Issue by gefaila** [influxdata/ui#3866] opened 2022-02-15 08:55 UTC
**Steps to reproduce:**
I have a Notebook that starts with a Query Builder.
I filter by a handful of _fields that I've selected, followed by a table and some charts.
Whenever I load the Notebook it runs correctly.

*HOWEVER* the UI refuses to display the list of _fields that were originally selected in the *FILTER* box of the Query Builder

As shown below (note the clock bottom right)
Note that the Notebook has already run and returned the correct data!
![image](https://user-images.githubusercontent.com/69196723/154025673-3fe07acd-90ce-40ca-b38b-36406775bb4c.png)
 
2 minutes later it has still not stopped "....Loading" the tags
![image](https://user-images.githubusercontent.com/69196723/154025849-3b6847f6-90fd-4696-b910-eb1d46f8a6f2.png)

After refreshing the page it still displays "...Loading".
![image](https://user-images.githubusercontent.com/69196723/154026129-ab4e277c-085e-4af9-8233-c528e6084749.png)

Only by typing something in the box does it now update and display the original tags *AND* the tags it's found due to what was typed.
![image](https://user-images.githubusercontent.com/69196723/154026769-1fe26191-3e1f-4cf1-bf14-dfaac8810f74.png)

**Expected behavior:**
All filter boxes should be populated when the Notebook is opened / run.

**Config:**
https://eu-central-1-1.aws.cloud2.influxdata.com/orgs/faac9e69ed04ee08/notebooks/5fa821932b640000

**Comment by asalem1** [comment] 2022-03-22 13:07
Hello @gefaila is this still an issue? I can't seem to reproduce it. I'm wondering if this may have been resolved by some previous work that's been done to enhance the user query experience in notebooks.

**Comment by asalem1** [comment] 2022-04-06 17:12
@gefaila I just merged in what _might_ be a fix (the reason I say maybe is that it's been super hard to track down the issue and duplicate it to some degree of consistency). The new UI image is going to be deployed later today, please let me know if you're still seeing the issue. I'm going to leave the issue open until we can confirm its gone for good

**Comment by jzahnd** [comment] 2022-04-25 17:29
@gefaila any feedback on the update above? We are happy to follow up but want to check in on the latest updates.

**Comment by gefaila** [comment] 2022-04-25 18:09
It's still happening,
Just hadn't had time to follow up

Cheers

Andrew

**Comment by gefaila** [comment] 2022-04-26 13:32
I see this when I go to a saved notebook.
![image](https://user-images.githubusercontent.com/69196723/165310938-7e1bd3c4-d9f0-4579-bad5-a62c3c1be156.png)

It *NEVER* actually loads the (1) tag value it knows you've selected until you type something in the filter box
If you type something and then delete it.  *THEN* it displays the (1) tag value the user was expecting to be ticked
![image](https://user-images.githubusercontent.com/69196723/165311295-d416bd64-8314-4eec-9a70-ca830650e75a.png)

**Comment by asalem1** [comment] 2022-04-27 18:59
@gefaila thanks for verifying that this is still in fact an issue. I just pushed up a change here:

https://github.com/influxdata/ui/pull/4466

That _should_ address the root cause of the issue. Please let me know if you're still seeing this issue

**Closed** 2022-05-10 22:11 UTC
Labels: kind/bug, team/ui, severity/sev-4, area/notebooks, team/unity
