### ISSUE TITLE
Maps: Maps visualization options doesn't display in notebooks

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1940] opened 2021-07-07 20:41 UTC
to repro, create a new notebook, remove the existing cells, add a raw flux editor panel and a visualization panel, choose maps in the viz panel, remove the aggregation, and enter the following query into the raw flux editor:

```
import "experimental/csv"
csv.from(url: "https://raw.githubusercontent.com/influxdata/influxdb2-sample-data/master/usgs-earthquake-data/all_week-annotated.csv")
```

then click preview at the top

Clicking on the gearbox in the viz panel then shows the following error:

 `TypeError: Cannot read property 'colors' of undefined`

![image (70)](https://user-images.githubusercontent.com/4805997/124825444-7df7a680-df28-11eb-9c99-4a756adb3b2d.png)

**Comment by kristinarobinson** [comment] 2021-07-09 19:19
duplicate of ui#1951.  closing

**Closed by kristinarobinson** 2021-07-09 19:19 UTC
Labels: kind/bug, team/ui
