### ISSUE TITLE
Make sure single stat visualizations can be cloned within dashboards.

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#3312] opened 2021-11-24 03:34 UTC
A customer had a dashboard that became unusable when they cloned a single stat cell.  The underlying cause ended up being the options were not stored correctly for the dashboard cell.  Since the name and graph options were not stored for the single stat, when it was cloned, the dashboard crashed trying to render the new cloned "corrupted" cell.

Please verify that the options are stored correctly.  You can use a curl command to call the API directly and inspect dashboard cells as follows:

```
curl --request GET http://localhost:8086/api/v2/dashboards/{dashboardID}? \
  --header "Authorization: Token INFLUX_API_TOKEN"
```
  
If the new single stat cell look the same as the other dashboard cells, and can be cloned on a dashboard with the clones also looking the same as other cells, then this issue can be closed with no further action.

**Comment by TCL735** [comment] 2022-01-07 00:16
I am unable to reproduce this problem locally.

I can clone a single stat cell just. I can also clone a dashboard that has a single stat cell. The cloned dashboard's single stat cell works just fine, too.

**Comment by TCL735** [comment] 2022-01-07 00:39
I am also unable to reproduce the problem in Tools.

I can clone a single stat cell and the clone works just fine. I can also clone a dashboard that has a single stat cell. The cloned dashboard's single stat cell works just fine, too.

**Comment by TCL735** [comment] 2022-01-08 01:02
Since we are unable to reproduce, closing this.

**Closed by TCL735** 2022-01-08 01:02 UTC
Labels: kind/bug, team/ui, team/dumplings
