### ISSUE TITLE
Bug: Table Customize sidebar crashes when editing

### ISSUE THREAD

**Issue by philjb** [influxdata/ui#3864] opened 2022-02-15 01:38 UTC
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Create a query that returns some data that can populate a Table visualization. See example query.
2. Click `Customize`
3. Add parameters for new color thresholds
4. Change the sort column (or other action).
5. Observe the page freeze and then show the "an error has occurred; please report it" message

I'm not sure of the exact order of operations but it appears related to thresholds and the sort column.

```
import "csv"

csvData = "
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,string,string,double
#group,false,false,false,false,false,false,false,false
#default,,,,,,,,
,result,table,_start,_stop,_time,region,host,_value
,mean,0,2018-05-08T20:50:00Z,2018-05-08T20:51:00Z,2018-05-08T20:50:00Z,east,A,15.43
,mean,0,2018-05-08T20:50:00Z,2018-05-08T20:51:00Z,2018-05-08T20:50:20Z,east,B,59.25
,mean,0,2018-05-08T20:50:00Z,2018-05-08T20:51:00Z,2018-05-08T20:50:40Z,east,C,52.62
"

csv.from(csv: csvData) |> last()
```

**Expected behavior:**
I can modify Customize settings in any order as many times as i like and the page doesn't crash.

**Actual behavior:**
Modal crash; sometimes the entire page freezes and the cpu spins up.

**Visual Proof:**

![Screen Shot 2022-02-14 at 5 21 16 PM](https://user-images.githubusercontent.com/13472206/153974964-637c29f9-cbf5-423d-a8c8-8b1127c16510.png)

![bug](https://user-images.githubusercontent.com/13472206/153976443-873269dc-4a2d-4eb8-9f21-d476c775f848.gif)

## About your environment

**Environment info:**

Influxdb internal and us-central

verified on both firefox and safari

**Config:**

na

**Logs:**

![Screen Shot 2022-02-14 at 5 21 00 PM](https://user-images.githubusercontent.com/13472206/153974947-8c0302da-ad42-4df5-8f1c-b3e52c520dc2.png)

**Performance:**
na

**Comment by kristinarobinson** [comment] 2022-02-26 00:09
Possibly a duplicate of https://github.com/influxdata/ui/issues/3343

**Comment by Luckette** [comment] 2022-02-28 19:18
UI#3343 may solve this problem

**Closed** 2022-03-03 21:31 UTC
Labels: kind/bug, team/ui, team/dumplings
