### ISSUE TITLE
Not displaying the group keys in raw data view correctly 

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/ui#4620] opened 2022-05-19 16:35 UTC
## Group functions are correctly transforming data, but the change in group keys isn't being reflected in the raw data view. 

**Steps to reproduce:**

1. Query for data
2. Change the group keys with the group() function  

**Expected behavior:**
I expect to see a change in the group keys in the raw data view. 

**Actual behavior:**
The group keys didn't change. Specifically on topic and generationID columns

**Visual Proof:**
raw data without the group
<img width="1236" alt="Screen Shot 2022-05-19 at 9 29 56 AM" src="https://user-images.githubusercontent.com/30506042/169352075-bc02dae1-6092-4b3a-8b0d-3d1868d3046f.png">

data with the group 
<img width="1227" alt="Screen Shot 2022-05-19 at 9 34 36 AM" src="https://user-images.githubusercontent.com/30506042/169352163-9f64df9c-bd99-4f1d-9fc1-311a7a7d62ed.png">

## About your environment

Cloud

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by TCL735** [comment] 2022-07-15 22:50
@Anaisdg are you still having this issue? We cannot reproduce it. Please let us know so that we may investigate further or close this out.

**Comment by Anaisdg** [comment] 2022-08-03 17:09
I am only having this issue with a specific dataset that gets written to InfluxDB with a task. Otherwise I don't have this issue.

**Comment by Anaisdg** [comment] 2022-08-03 17:14
The data comes from:
https://github.com/InfluxCommunity/InfluxDB-Roadshow-Training

**Comment by TCL735** [comment] 2022-09-30 20:47
There isn't an issue here. Under each column there is a "Group" or "No Group" description. It's based on your query.

If you feel there is still an issue, please open a new issue and attach the csv that comes from the Network Tab for the response when you make this query.

**Closed by TCL735** 2022-09-30 20:47 UTC
Labels: kind/bug, team/ui, team/dumplings
